// =====================================================================
//  GEOGRAFIA IRADA — eventos do Jornal Mundial ("Plantão Global")
// =====================================================================
//  A cada mandato sai 1 evento (2 se o mundo estiver em crise). Campos:
//   tipo: 'clima' | 'crise' | 'conflito' | 'migracao' | 'recursos' | 'politica' | 'positivo'
//   local: id de território/potência, ou { entre: [ids], conflitoMin, estabilidadeMax, vulnerabilidadeMin }
//          (num mesmo evento, só territórios ou só potências: o caminho 'local.x' precisa existir no lugar)
//   peso: chance base · condicoes: [{ v: 'global.temperatura', min: 1.7, x: 2 }] multiplicam a chance
//         (v também pode ser 'territorio.<id>.<campo>', 'conflitos' ou 'rodada'; com exige: true,
//         o evento só sai se a condição valer) · unico: sai só uma vez · rodadaMin
//   efeitos: como nas políticas, com 'local.x' (o lugar do evento), 'vizinhos.x' (territórios vizinhos do lugar),
//            escala: 'clima' (pior quanto mais quente) e vuln: true (pior quanto mais vulnerável)
//   escolha: null | { tipo: 'votacao', resolucao } | { tipo: 'doacao', recurso, meta, sucesso, fracasso }
//            | { tipo: 'decisao', opcoes, coletivo? }: cada potência escolhe uma opção (Simulacao.resolverDecisao)
//              opcoes: [{ texto (≤ 140), resumo (≤ 40), categoria, efeitos (sem prefixo = quem escolheu), porque, manchete }]
//              (na manchete, {quem}, {de quem}, {em local}… e {verbo|verbos} como em dilemas.js)
//              coletivo: { opcao, min, efeitos, manchete, motivo, senao?, mancheteSenao?, motivoSenao? }: se pelo
//              menos "min" potências escolherem a mesma "opcao", o mundo todo sente (ação coletiva); senão, vale o "senao"
//   temas: baralhos ligados (foco da aula) · bncc · vocesabia (fato verificado, com ano e fonte)
//  Dentro dos textos, use ’ e “ ” (nunca ' ou ").
// =====================================================================

const EVENTOS = [
  // ---------------- 🌡️ CLIMA ----------------
  { id: 'onda_calor', titulo: 'Onda de calor recorde', icone: '🌡️', tipo: 'clima', temas: ['natureza', 'pessoas'], local: 'india',
    texto: 'Os termômetros passam dos 45 °C na Índia e nos países vizinhos. Hospitais lotam, plantações secam e a energia falta nas horas mais quentes do dia.',
    peso: 1, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }, { v: 'global.temperatura', min: 1.9, x: 1.5 }],
    efeitos: [{ v: 'local.bemEstar', d: -3, escala: 'clima', vuln: true }, { v: 'local.economia', d: -2, escala: 'clima', vuln: true },
      { v: 'vizinhos.estabilidade', d: -3, escala: 'clima', vuln: true }, { v: 'global.energia', d: 2 }],
    manchete: 'Calor extremo bate recordes no sul da Ásia e testa os limites da adaptação',
    bncc: ['EM13CHS306', 'EM13CHS201', 'EM13CNT203'],
    vocesabia: '2024 foi o ano mais quente já medido, cerca de 1,6 °C acima da era pré-industrial (Copernicus). Um ano só não rompe a meta de Paris, que vale para a média de longo prazo, mas cada fração de grau a mais deixa as ondas de calor mais frequentes e intensas (IPCC, 2023).' },
  { id: 'seca_amazonia', titulo: 'Seca histórica na Amazônia', icone: '🏜️', tipo: 'clima', temas: ['natureza'], local: 'brasil',
    texto: 'Rios da Amazônia baixam a níveis recordes e o fogo avança sobre a floresta seca. Comunidades ficam isoladas, botos morrem e as hidrelétricas produzem menos.',
    peso: .8, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }],
    efeitos: [{ v: 'local.ambiente', d: -4, escala: 'clima' }, { v: 'local.economia', d: -2, escala: 'clima' }, { v: 'local.recursos.energia', d: -1 },
      { v: 'local.desmatamento', d: .1 }, { v: 'global.temperatura', d: .02, escala: 'clima' }], // floresta que seca e queima solta carbono: ponto de virada
    manchete: 'Seca na Amazônia isola comunidades e reduz geração das hidrelétricas',
    bncc: ['EM13CHS302', 'EM13CHS306', 'EM13CNT206'],
    vocesabia: 'Em 2023 e de novo em 2024, o Rio Negro, em Manaus, chegou ao nível mais baixo desde o início das medições, em 1902 (Serviço Geológico do Brasil).' },
  { id: 'furacao', titulo: 'Ciclone tropical devastador', icone: '🌀', tipo: 'clima', temas: ['natureza', 'pessoas'],
    local: { entre: ['caribe', 'america_central', 'mexico', 'sudeste_insular', 'sul_asia', 'pacifico'] },
    texto: 'Ventos de mais de 250 km/h destroem casas, portos e plantações. É o mesmo fenômeno chamado de furacão nas Américas, tufão no leste da Ásia e ciclone no Índico e no Pacífico Sul.',
    peso: 1, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 1.8 }],
    efeitos: [{ v: 'local.estabilidade', d: -8, escala: 'clima', vuln: true }, { v: 'local.desenvolvimento', d: -3, escala: 'clima', vuln: true },
      { v: 'global.deslocados', d: 4 }],
    escolha: { tipo: 'doacao', recurso: 'alimentos', meta: 5,
      sucesso: [{ v: 'local.estabilidade', d: 8 }, { v: 'global.deslocados', d: -3 }, { v: 'global.cooperacao', d: 2 }],
      fracasso: [{ v: 'local.estabilidade', d: -5 }, { v: 'global.deslocados', d: 3 }] },
    manchete: 'Ciclone devastador deixa milhares de desabrigados',
    bncc: ['EM13CHS306', 'EM13CHS201', 'EM13CHS605', 'EM13CHS501'],
    vocesabia: 'Oceanos mais quentes alimentam ciclones mais fortes, e o IPCC (2021) projeta uma proporção maior de ciclones de categorias 4 e 5 com o aquecimento. Em 2004, o Catarina, primeiro furacão registrado no Atlântico Sul, chegou à costa no sul de Santa Catarina e atingiu também o norte do Rio Grande do Sul (NOAA; INPE).' },
  { id: 'mar_sobe', titulo: 'O mar avança sobre as ilhas', icone: '🌊', tipo: 'clima', temas: ['natureza', 'pessoas'], local: 'pacifico',
    texto: 'Marés altas invadem casas e salgam a água doce. Famílias deixam suas ilhas, mas a Convenção dos Refugiados, de 1951, não reconhece como refugiado quem foge só por causa do clima.',
    peso: .6, condicoes: [{ v: 'global.temperatura', min: 1.7, x: 3 }],
    efeitos: [{ v: 'local.estabilidade', d: -6, escala: 'clima' }, { v: 'local.desenvolvimento', d: -3, escala: 'clima' }, { v: 'global.deslocados', d: 1 }],
    manchete: 'Subida do mar força famílias a deixar ilhas do Pacífico',
    bncc: ['EM13CHS201', 'EM13CHS306', 'EM13CHS605'],
    vocesabia: 'Em 2023, Tuvalu e Austrália assinaram a União Falepili, que abre caminho para até 280 tuvaluanos por ano se mudarem para a Austrália: um dos primeiros acordos de mobilidade por causa do clima (governo da Austrália).' },
  { id: 'enchentes', titulo: 'Enchentes históricas', icone: '🌧️', tipo: 'clima', temas: ['natureza', 'pessoas'],
    local: { entre: ['afeg_paquistao', 'sul_asia', 'africa_oriental', 'africa_ocidental', 'sudeste_continental', 'norte_africa', 'cone_sul', 'africa_austral'] },
    texto: 'Em poucos dias, chove o que se esperava para meses. Rios transbordam, pontes caem e bairros inteiros ficam submersos. Os abrigos lotam e falta comida.',
    peso: 1, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }, { v: 'global.temperatura', min: 1.9, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -7, escala: 'clima', vuln: true }, { v: 'local.desenvolvimento', d: -3, escala: 'clima', vuln: true },
      { v: 'global.deslocados', d: 4, escala: 'clima' }],
    escolha: { tipo: 'doacao', recurso: 'alimentos', meta: 5,
      sucesso: [{ v: 'local.estabilidade', d: 7 }, { v: 'global.deslocados', d: -3 }, { v: 'global.cooperacao', d: 2 }],
      fracasso: [{ v: 'local.estabilidade', d: -4 }, { v: 'global.deslocados', d: 2 }] },
    manchete: 'Enchentes históricas deixam milhões de pessoas fora de casa',
    bncc: ['EM13CHS306', 'EM13CHS201', 'EM13CHS606'],
    vocesabia: 'Em 2024, as enchentes no Rio Grande do Sul atingiram 478 dos 497 municípios, com mais de 180 mortes e cerca de 2,4 milhões de pessoas afetadas: a maior catástrofe climática da história do estado (Defesa Civil do RS).' },
  { id: 'incendios', titulo: 'Incêndios florestais fora de controle', icone: '🔥', tipo: 'clima', temas: ['natureza'],
    local: { entre: ['canada', 'australia', 'cone_sul', 'andes', 'sudeste_insular'] },
    texto: 'Depois de meses de calor e seca, o fogo devora florestas e chega às cidades. A fumaça atravessa fronteiras e deixa o céu alaranjado a milhares de quilômetros.',
    peso: .9, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }, { v: 'global.temperatura', min: 1.9, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -5, escala: 'clima' }, { v: 'local.desenvolvimento', d: -2, escala: 'clima' },
      { v: 'vizinhos.estabilidade', d: -1, escala: 'clima' }, { v: 'global.deslocados', d: 1 }, { v: 'global.temperatura', d: .015, escala: 'clima' }], // o fogo devolve carbono ao ar
    manchete: 'Incêndios recordes queimam florestas e espalham fumaça por milhares de quilômetros',
    bncc: ['EM13CHS304', 'EM13CHS306', 'EM13CNT206'],
    vocesabia: 'Em 2023, o Canadá teve a pior temporada de incêndios já registrada: mais de 18 milhões de hectares queimados, quase o dobro da área de Santa Catarina. A fumaça chegou a Nova York e à Europa (governo do Canadá; CIFFC).' },
  { id: 'degelo_artico', titulo: 'O Ártico derrete e abre novas rotas', icone: '🧊', tipo: 'clima', temas: ['natureza', 'territorio', 'globalizacao'], local: 'groenlandia',
    texto: 'No verão, o gelo do mar Ártico encolhe e navios cruzam rotas antes congeladas. Mineradoras e marinhas chegam junto, e o gelo que derrete na Groenlândia faz o mar subir no mundo todo.',
    peso: .7, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }],
    efeitos: [{ v: 'global.comercio', d: 2 }, { v: 'local.recursos.minerais', d: 1 }, { v: 'local.pressao', d: 10 }, { v: 'global.tensao', d: 3 },
      { v: 'territorios.vulnerabilidade', d: 1 }, { v: 'global.temperatura', d: .015, escala: 'clima' }], // menos gelo, menos luz refletida: o aquecimento se alimenta
    manchete: 'Degelo abre rotas no Ártico e acende a disputa por minérios',
    bncc: ['EM13CHS203', 'EM13CHS306', 'EM13CHS103', 'EM13MAT101'],
    vocesabia: 'Desde 1979, o gelo do mar Ártico no fim do verão encolhe cerca de 12% por década (NASA). Esse gelo já flutua e não eleva o mar ao derreter; o da Groenlândia, que fica sobre a terra, sim: desde 2002, ela perde cerca de 266 bilhões de toneladas de gelo por ano (NASA).' },

  // ---------------- 🚨 CRISES ----------------
  { id: 'crise_petroleo', titulo: 'Crise no Estreito de Ormuz', icone: '🛢️', tipo: 'crise', temas: ['globalizacao', 'conflitos'], local: 'golfo',
    texto: 'Ameaças ao tráfego de petroleiros no Estreito de Ormuz, por onde passa cerca de um quinto do petróleo do mundo, fazem o preço disparar. No Brasil, diesel e frete ficam mais caros.',
    peso: .9, condicoes: [{ v: 'global.tensao', min: 75, x: 2 }, { v: 'territorio.ira.conflito', min: 1, x: 1.5 }],
    efeitos: [{ v: 'global.energia', d: 14 }, { v: 'global.tensao', d: 3 }, { v: 'global.comercio', d: -3 }],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Liberar parte dos estoques de emergência de petróleo.', resumo: 'Liberar estoques', categoria: 'economia',
          efeitos: [{ v: 'recursos.energia', d: -1 }, { v: 'global.energia', d: -2 }, { v: 'global.cooperacao', d: 1 }],
          porque: 'Estoque é seguro para a hora da crise: soltar petróleo no mercado segura o preço, e o efeito é muito maior quando vários países fazem juntos.',
          manchete: '{quem} {libera|liberam} estoques de petróleo para conter o preço' },
        { texto: 'Acelerar a energia limpa para depender menos do petróleo.', resumo: 'Acelerar a energia limpa', categoria: 'natureza',
          efeitos: [{ v: 'limpa', d: 4 }, { v: 'economia', d: -2 }],
          porque: 'A crise mostra o custo de depender do petróleo: sol e vento custam agora e protegem nas próximas crises.',
          manchete: '{quem} {responde|respondem} à crise acelerando a energia limpa' },
        { texto: 'Subsidiar o combustível para a população não sentir.', resumo: 'Subsidiar o combustível', categoria: 'pessoas',
          efeitos: [{ v: 'apoio', d: 2 }, { v: 'economia', d: -2 }, { v: 'fossil', m: 1.02 }],
          porque: 'O subsídio protege o bolso agora, mas sai do orçamento e mantém o consumo de petróleo alto.',
          manchete: '{quem} {subsidia|subsidiam} combustíveis em meio à alta do petróleo' },
      ],
      coletivo: { opcao: 0, min: 4, efeitos: [{ v: 'global.energia', d: -8 }, { v: 'global.cooperacao', d: 2 }], motivo: 'liberação coordenada de estoques',
        manchete: 'Liberação coordenada de estoques derruba o preço do petróleo' } },
    manchete: 'Petróleo dispara com tensão no Estreito de Ormuz',
    bncc: ['EM13CHS201', 'EM13CHS204', 'EM13CNT309'],
    vocesabia: 'Em 2024, passaram pelo Estreito de Ormuz cerca de 20 milhões de barris de petróleo por dia, o equivalente a 20% do consumo mundial (EIA, agência de energia dos EUA). Em 2026, com a guerra do Irã, a Agência Internacional de Energia coordenou a liberação de 400 milhões de barris dos estoques dos países.' },
  { id: 'pandemia', titulo: 'Surto de uma nova doença', icone: '🦠', tipo: 'crise', temas: ['pessoas', 'globalizacao'], local: null, unico: true, rodadaMin: 2,
    texto: 'Um vírus respiratório novo se espalha por aeroportos do mundo inteiro. Cientistas correm para desenvolver vacinas.',
    peso: .6,
    efeitos: [{ v: 'todos.bemEstar', d: -4, imune: 'pandemia' }, { v: 'todos.economia', d: -3, imune: 'pandemia' }, { v: 'global.comercio', d: -6 }],
    escolha: { tipo: 'votacao', resolucao: 'fundo_vacinas' },
    manchete: 'Nova doença se espalha e a OMS pede cooperação internacional',
    bncc: ['EM13CHS202', 'EM13CHS604', 'EM13CNT310'],
    vocesabia: 'Em maio de 2025, os países da OMS adotaram um Acordo sobre Pandemias para dividir melhor vacinas e informações. Mas a OMS não pode obrigar nenhum país a fechar fronteiras ou a vacinar: ela coordena e recomenda (OMS).' },
  { id: 'ciberataque', titulo: 'Ciberataque causa apagão', icone: '💻', tipo: 'crise', temas: ['globalizacao', 'conflitos'],
    local: { entre: ['brasil', 'eua', 'china', 'ue', 'india', 'russia'] },
    texto: 'Hackers invadem os sistemas de hospitais, bancos e da rede elétrica. Cidades inteiras ficam no escuro por horas, e ninguém assume a autoria do ataque.',
    peso: 1, condicoes: [{ v: 'global.tensao', min: 70, x: 1.5 }],
    efeitos: [{ v: 'local.economia', d: -3, imune: 'ciber' }, { v: 'local.seguranca', d: -4, imune: 'ciber' }, { v: 'local.apoio', d: -2, imune: 'ciber' },
      { v: 'global.tensao', d: 2 }],
    manchete: 'Ciberataque apaga cidades e derruba serviços essenciais',
    bncc: ['EM13CHS202', 'EM13CHS504', 'EM13CNT106'],
    vocesabia: 'Em dezembro de 2015, hackers desligaram 30 subestações na Ucrânia e deixaram cerca de 225 mil consumidores sem luz por horas: foi o primeiro ciberataque a uma rede elétrica reconhecido publicamente (CISA, agência dos EUA; revista Wired).' },
  { id: 'desinformacao', titulo: 'Onda de desinformação', icone: '📱', tipo: 'crise', temas: ['pessoas'], local: null,
    texto: 'Uma notícia falsa e bombástica viraliza nas redes de todos os países: vídeos montados, contas automáticas e grupos de mensagens. Cada governo precisa decidir como reagir.',
    peso: 1, efeitos: [],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Exigir que as plataformas removam o conteúdo falso e mostrem quem paga os anúncios.', resumo: 'Regular as plataformas', categoria: 'seguranca',
          efeitos: [{ v: 'imune.desinfo', d: 2 }, { v: 'seguranca', d: 1 }, { v: 'apoio', d: -1 }],
          porque: 'Regras para as plataformas cortam a onda rápido, mas cada remoção reabre o debate sobre liberdade de expressão.',
          manchete: '{quem} {obriga|obrigam} plataformas a remover a notícia falsa' },
        { texto: 'Campanha de checagem de fatos e educação midiática.', resumo: 'Checagem e educação', categoria: 'ciencia',
          efeitos: [{ v: 'economia', d: -1 }, { v: 'imune.desinfo', d: 1 }, { v: 'apoio', d: 1 }],
          porque: 'Quem aprende a checar fonte, data e autor cai menos na próxima mentira. Funciona devagar e custa dinheiro.',
          manchete: '{quem} {lança|lançam} campanha de checagem de fatos' },
        { texto: 'Ignorar: a mentira some sozinha.', resumo: 'Ignorar', categoria: 'economia',
          efeitos: [{ v: 'apoio', d: -4, imune: 'desinfo' }, { v: 'seguranca', d: -1, imune: 'desinfo' }],
          porque: 'Sem resposta, a mentira corre mais rápido que a verdade e corrói a confiança no governo, a não ser que o país já tenha se preparado antes.',
          manchete: 'Notícia falsa se espalha sem resposta {em quem}' },
      ],
      coletivo: { opcao: 1, min: 4, efeitos: [{ v: 'global.cooperacao', d: 2 }, { v: 'global.tensao', d: -1 }], motivo: 'checagem conjunta',
        manchete: 'Checadores de vários países desmontam a notícia falsa juntos' } },
    manchete: 'Notícia falsa viraliza no mundo inteiro',
    bncc: ['EM13CHS202', 'EM13CHS106', 'EM13LP39', 'EM13LP40'],
    vocesabia: 'Notícias falsas se espalham mais rápido que as verdadeiras: no Twitter, elas tinham 70% mais chance de ser compartilhadas (MIT, revista Science, 2018). Checar fonte, data e autor e procurar a notícia em outros veículos ajuda a não cair.' },
  { id: 'crise_alimentar', titulo: 'Crise alimentar global', icone: '🌾', tipo: 'crise', temas: ['globalizacao', 'pessoas'],
    local: { entre: ['africa_oriental', 'sahel', 'afeg_paquistao', 'caribe', 'levante'] },
    texto: 'Secas e guerras derrubam colheitas e o preço do trigo e do arroz dispara. Agências da ONU pedem doações urgentes.',
    peso: .9, condicoes: [{ v: 'global.temperatura', min: 1.7, x: 1.5 }, { v: 'conflitos', min: 6, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -8 }, { v: 'global.deslocados', d: 4 }],
    escolha: { tipo: 'doacao', recurso: 'alimentos', meta: 6,
      sucesso: [{ v: 'local.estabilidade', d: 10 }, { v: 'local.desenvolvimento', d: 2 }, { v: 'global.deslocados', d: -5 }, { v: 'global.cooperacao', d: 3 }],
      fracasso: [{ v: 'local.estabilidade', d: -6 }, { v: 'global.deslocados', d: 4 }, { v: 'local.conflito', d: 1, chance: .5 }] },
    manchete: 'Preço dos alimentos dispara e a fome volta a crescer',
    bncc: ['EM13CHS201', 'EM13CHS605', 'EM13CHS306'],
    vocesabia: 'O Programa Mundial de Alimentos da ONU ganhou o Nobel da Paz de 2020 por combater a fome e tentar impedir que ela seja usada como arma de guerra (Comitê Nobel Norueguês).' },
  { id: 'crise_divida', titulo: 'Crise da dívida', icone: '💸', tipo: 'crise', temas: ['globalizacao', 'ordem'],
    local: { entre: ['africa_oriental', 'africa_ocidental', 'africa_austral', 'sul_asia', 'cone_sul', 'andes', 'levante', 'norte_africa', 'afeg_paquistao'] },
    texto: 'Com juros altos e o dólar caro, o governo não consegue pagar o que deve a credores estrangeiros. Faltam combustível e remédios, e o FMI pede cortes de gastos em troca de um empréstimo.',
    peso: .8, condicoes: [{ v: 'global.comercio', max: 50, x: 1.5 }, { v: 'global.energia', min: 70, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -8 }, { v: 'local.desenvolvimento', d: -3 }, { v: 'local.pressao', d: 10 }, { v: 'global.comercio', d: -1 }],
    escolha: { tipo: 'doacao', recurso: 'energia', meta: 4,
      sucesso: [{ v: 'local.estabilidade', d: 7 }, { v: 'global.cooperacao', d: 2 }],
      fracasso: [{ v: 'local.estabilidade', d: -4 }, { v: 'local.conflito', d: 1, chance: .3 }] },
    manchete: 'País deixa de pagar a dívida externa e negocia socorro com o FMI',
    bncc: ['EM13CHS201', 'EM13CHS604', 'EM13CHS402', 'EM13CHS102'],
    vocesabia: 'Em abril de 2022, o Sri Lanka deixou de pagar a dívida externa pela primeira vez desde a independência, em 1948. Faltaram combustível e remédios, e protestos em massa levaram à renúncia do presidente (FMI; BBC).' },
  { id: 'cabos_submarinos', titulo: 'Cabos submarinos rompidos', icone: '🔌', tipo: 'crise', temas: ['globalizacao', 'territorio'],
    local: { entre: ['norte_africa', 'golfo', 'taiwan', 'sudeste_insular', 'africa_ocidental'] },
    texto: 'Cabos de internet no fundo do mar se rompem. Bancos, escolas e empresas de vários países ficam fora do ar até a chegada dos navios de reparo. Foi acidente ou sabotagem?',
    peso: .7, condicoes: [{ v: 'global.tensao', min: 75, x: 1.5 }],
    efeitos: [{ v: 'local.desenvolvimento', d: -2 }, { v: 'local.estabilidade', d: -3 }, { v: 'global.comercio', d: -2 }, { v: 'global.tensao', d: 2 }],
    manchete: 'Cabos submarinos rompidos deixam milhões de pessoas sem internet',
    bncc: ['EM13CHS202', 'EM13CHS206', 'EM13CHS106'],
    vocesabia: 'Há mais de 600 cabos submarinos ativos ou planejados, e eles levam quase todos os dados entre continentes: nos EUA, satélites respondem por só 0,37% da capacidade internacional. Âncoras e redes de pesca causam dois terços dos cerca de 200 rompimentos por ano (TeleGeography, 2026).' },
  { id: 'mar_vermelho', titulo: 'Ataques no Mar Vermelho', icone: '⚓', tipo: 'crise', temas: ['globalizacao', 'conflitos'], local: 'norte_africa',
    texto: 'Navios mercantes são atacados na entrada do Mar Vermelho. Muitas empresas evitam o Canal de Suez e contornam a África, numa viagem até duas semanas mais longa, e o Egito perde boa parte da renda do canal.',
    peso: .8, condicoes: [{ v: 'global.tensao', min: 75, x: 1.5 }, { v: 'territorio.golfo.conflito', min: 1, x: 1.3 }],
    efeitos: [{ v: 'global.comercio', d: -4 }, { v: 'global.energia', d: 3 }, { v: 'global.tensao', d: 2 }, { v: 'local.desenvolvimento', d: -2 },
      { v: 'local.estabilidade', d: -2 }],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Mandar navios de guerra para escoltar os mercantes.', resumo: 'Escoltar navios', categoria: 'seguranca',
          efeitos: [{ v: 'militar', d: 3 }, { v: 'economia', d: -1 }, { v: 'global.tensao', d: 1 }],
          porque: 'Escoltas mantêm a rota aberta, mas mais navios armados na região aumentam o risco de confronto.',
          manchete: '{quem} {envia|enviam} navios de guerra para o Mar Vermelho' },
        { texto: 'Desviar a carga pelo sul da África.', resumo: 'Contornar a África', categoria: 'economia',
          efeitos: [{ v: 'economia', d: -1 }],
          porque: 'Contornar a África é seguro, mas a viagem fica até duas semanas mais longa e o frete encarece para todos.',
          manchete: 'Navios {de quem} contornam a África para fugir dos ataques' },
        { texto: 'Pressionar por negociação de paz no Iêmen.', resumo: 'Pressionar pela paz', categoria: 'diplomacia',
          efeitos: [{ v: 'global.cooperacao', d: 1 }, { v: 'global.tensao', d: -1 }, { v: 'apoio', d: -1 }],
          porque: 'Os ataques no mar nascem da guerra em terra: tratar a causa é mais lento, mas é o que reabre a rota de vez.',
          manchete: '{quem} {pressiona|pressionam} por paz no Iêmen para reabrir o Mar Vermelho' },
      ],
      coletivo: { opcao: 0, min: 3, efeitos: [{ v: 'global.comercio', d: 3 }], motivo: 'escolta internacional',
        manchete: 'Escolta internacional reabre a rota do Mar Vermelho' } },
    manchete: 'Ataques a navios esvaziam o Canal de Suez e encarecem o frete',
    bncc: ['EM13CHS201', 'EM13CHS206', 'EM13CHS204'],
    vocesabia: 'O Canal de Suez é um gargalo do comércio mundial: em 2021, o navio Ever Given encalhou ali e travou a passagem por seis dias, e cerca de US$ 9,6 bilhões em mercadorias ficaram parados a cada dia (Lloyd’s List).' },
  { id: 'canal_panama', titulo: 'Seca trava o Canal do Panamá', icone: '🛳️', tipo: 'crise', temas: ['globalizacao', 'natureza'], local: 'america_central',
    texto: 'Sem chuva, baixa o lago que abastece as eclusas do Canal do Panamá. A passagem de navios é limitada, filas se formam no mar e o frete entre os oceanos fica mais caro.',
    peso: .7, condicoes: [{ v: 'global.temperatura', min: 1.6, x: 2 }],
    efeitos: [{ v: 'global.comercio', d: -3, escala: 'clima' }, { v: 'local.desenvolvimento', d: -2 }, { v: 'local.estabilidade', d: -2 }],
    manchete: 'Seca histórica reduz a passagem de navios pelo Canal do Panamá',
    bncc: ['EM13CHS201', 'EM13CHS206', 'EM13CHS306'],
    vocesabia: 'Cada navio que cruza o Canal do Panamá usa, em média, cerca de 200 milhões de litros de água doce nas eclusas. Por isso, secas como a de 2023 obrigam o canal a limitar o número de navios por dia (Autoridade do Canal do Panamá).' },

  // ---------------- 💥 CONFLITOS E TENSÕES ----------------
  { id: 'golpe_sahel', titulo: 'Golpe de Estado', icone: '⚠️', tipo: 'conflito', temas: ['conflitos', 'ordem'],
    local: { entre: ['sahel', 'africa_ocidental', 'africa_central', 'venezuela_guianas', 'sudeste_continental'], estabilidadeMax: 45 },
    texto: 'Militares tomam o poder, fecham o parlamento e expulsam diplomatas estrangeiros. A população vive dias de incerteza.',
    peso: 1, condicoes: [{ v: 'global.tensao', min: 70, x: 1.4 }],
    efeitos: [{ v: 'local.estabilidade', d: -12 }, { v: 'local.conflito', d: 1 }, { v: 'local.influencia', d: -2 }, { v: 'global.tensao', d: 3 },
      { v: 'global.deslocados', d: 2 }],
    escolha: { tipo: 'votacao', resolucao: 'missao_paz' },
    manchete: 'Golpe militar derruba governo e acende alerta regional',
    bncc: ['EM13CHS602', 'EM13CHS603', 'EM13CHS604'],
    vocesabia: 'Entre 2020 e 2023, Mali, Burkina Faso e Níger passaram por golpes militares. Os três criaram a Aliança dos Estados do Sahel em 2023 e, em janeiro de 2025, saíram da CEDEAO, o bloco da África Ocidental (CEDEAO).' },
  { id: 'escalada', titulo: 'Escalada de um conflito', icone: '💥', tipo: 'conflito', temas: ['conflitos'],
    local: { conflitoMin: 1 },
    texto: 'Os combates se intensificam. Civis fogem em massa e organizações humanitárias pedem um corredor seguro.',
    peso: 1.2, condicoes: [{ v: 'global.tensao', min: 75, x: 1.8 }, { v: 'global.cooperacao', max: 35, x: 1.5 }],
    efeitos: [{ v: 'local.conflito', d: 1 }, { v: 'local.estabilidade', d: -8 }, { v: 'global.deslocados', d: 6 }, { v: 'global.tensao', d: 4 }],
    escolha: { tipo: 'votacao', resolucao: 'missao_paz' },
    manchete: 'Conflito se agrava e milhares de civis buscam refúgio',
    bncc: ['EM13CHS503', 'EM13CHS605', 'EM13CHS201'],
    vocesabia: 'Guerras, violência e perseguição são a principal causa de deslocamento forçado: no fim de 2025, cerca de 118 milhões de pessoas viviam longe de casa por esses motivos, 1 em cada 70 pessoas no mundo (ACNUR, 2026).' },
  { id: 'taiwan_estreito', titulo: 'Tensão no Estreito de Taiwan', icone: '🚢', tipo: 'conflito', temas: ['conflitos', 'globalizacao'], local: 'taiwan',
    texto: 'Exercícios militares cercam a ilha e navios de carga mudam de rota. Fábricas do mundo inteiro temem ficar sem chips.',
    peso: .7, condicoes: [{ v: 'global.tensao', min: 70, x: 1.6 }],
    efeitos: [{ v: 'global.tensao', d: 6 }, { v: 'global.comercio', d: -4 }, { v: 'todos.recursos.tecnologia', d: -1 }],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Estocar chips e procurar outros fornecedores.', resumo: 'Estocar e diversificar', categoria: 'economia',
          efeitos: [{ v: 'economia', d: -1 }, { v: 'recursos.tecnologia', d: 1 }],
          porque: 'Estoque e fornecedores alternativos protegem as fábricas se a ilha parar, mas custam dinheiro parado.',
          manchete: '{quem} {corre|correm} para estocar chips' },
        { texto: 'Pedir publicamente diálogo e moderação a todos.', resumo: 'Pedir diálogo', categoria: 'diplomacia',
          efeitos: [{ v: 'global.tensao', d: -1 }, { v: 'apoio', d: -1 }],
          porque: 'Um pedido isolado pesa pouco; quando muitos países pedem juntos, ninguém quer ser visto como quem começou.',
          manchete: '{quem} {pede|pedem} diálogo no Estreito de Taiwan' },
        { texto: 'Mandar navios para a região.', resumo: 'Mandar navios', categoria: 'seguranca',
          efeitos: [{ v: 'militar', d: 3 }, { v: 'seguranca', d: 1 }, { v: 'global.tensao', d: 2 }],
          porque: 'Navios mostram que a rota importa, mas cada frota a mais no estreito aumenta a chance de um choque por engano.',
          manchete: '{quem} {envia|enviam} navios ao Estreito de Taiwan' },
      ],
      coletivo: { opcao: 1, min: 4, efeitos: [{ v: 'global.tensao', d: -4 }], motivo: 'pressão diplomática conjunta',
        manchete: 'Pressão diplomática conjunta esfria a crise no Estreito de Taiwan' } },
    manchete: 'Exercícios militares no Estreito de Taiwan ameaçam cadeia global de chips',
    bncc: ['EM13CHS202', 'EM13CHS204', 'EM13CHS603'],
    vocesabia: 'Em 2021, 92% da capacidade mundial de fabricar os chips mais avançados (menores que 10 nanômetros), usados em celulares e computadores de ponta, ficava em Taiwan; o resto, na Coreia do Sul (SIA/BCG, 2021).' },
  { id: 'coreia_misseis', titulo: 'Teste de míssil na Península Coreana', icone: '🚀', tipo: 'conflito', temas: ['conflitos', 'ordem'], local: 'coreia_norte',
    texto: 'A Coreia do Norte lança um míssil de longo alcance que cai no mar, perto do Japão. Sirenes tocam, voos são suspensos e a ONU convoca uma reunião de emergência.',
    peso: .7, condicoes: [{ v: 'global.tensao', min: 75, x: 1.6 }, { v: 'global.cooperacao', max: 35, x: 1.3 }],
    efeitos: [{ v: 'global.tensao', d: 6 }, { v: 'vizinhos.estabilidade', d: -3 }, { v: 'global.comercio', d: -1 }],
    escolha: { tipo: 'votacao', resolucao: 'tratado_desarmamento' },
    manchete: 'Míssil norte-coreano acende alerta no Leste da Ásia',
    bncc: ['EM13CHS604', 'EM13CHS504', 'EM13CHS603'],
    vocesabia: 'A Guerra da Coreia (1950–1953) terminou só com um armistício, sem tratado de paz, e as duas Coreias seguem divididas. Entre 2006 e 2017, a Coreia do Norte fez seis testes nucleares (CTBTO, organização do tratado que proíbe esses testes).' },
  { id: 'mar_sul_china', titulo: 'Tensão no Mar do Sul da China', icone: '🏝️', tipo: 'conflito', temas: ['conflitos', 'territorio', 'globalizacao'], local: 'sudeste_insular',
    texto: 'Navios de guarda costeira se enfrentam perto de recifes disputados por vários países. Por ali passa a rota que liga o Estreito de Malaca aos portos da China, do Japão e da Coreia.',
    peso: .7, condicoes: [{ v: 'global.tensao', min: 70, x: 1.6 }, { v: 'global.cooperacao', max: 35, x: 1.3 }],
    efeitos: [{ v: 'global.tensao', d: 4 }, { v: 'global.comercio', d: -3 }, { v: 'local.estabilidade', d: -3 }],
    manchete: 'Choques no Mar do Sul da China ameaçam uma das rotas mais movimentadas do mundo',
    bncc: ['EM13CHS204', 'EM13CHS603', 'EM13CHS206'],
    vocesabia: 'Em 2016, num caso aberto pelas Filipinas, um tribunal de arbitragem em Haia decidiu que as reivindicações chinesas baseadas na “linha de nove traços” não têm base no Direito do Mar. A China não reconhece a decisão (Corte Permanente de Arbitragem).' },
  { id: 'essequibo', titulo: 'Tensão no Essequibo', icone: '🗺️', tipo: 'conflito', temas: ['territorio', 'conflitos'], local: 'venezuela_guianas',
    texto: 'A Venezuela volta a reivindicar o Essequibo, região rica em recursos naturais que a Guiana administra. Tropas se movimentam, e o Brasil reforça a fronteira em Roraima.',
    peso: .6, condicoes: [{ v: 'global.tensao', min: 75, x: 1.5 }, { v: 'territorio.venezuela_guianas.estabilidade', max: 30, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -6 }, { v: 'local.conflito', d: 1, chance: .3 }, { v: 'global.tensao', d: 3 }],
    manchete: 'Disputa pelo Essequibo leva tensão à fronteira norte do Brasil',
    bncc: ['EM13CHS204', 'EM13CHS603', 'EM13CHS604'],
    vocesabia: 'Em 1º de dezembro de 2023, a Corte Internacional de Justiça mandou a Venezuela não alterar a situação no Essequibo, controlado pela Guiana. Dois dias depois, a Venezuela fez um referendo sobre a região (CIJ).' },
  { id: 'guerra_sudao', titulo: 'Guerra e fome no Sudão', icone: '🆘', tipo: 'conflito', temas: ['conflitos', 'pessoas'], local: 'africa_oriental',
    texto: 'O exército e um grupo paramilitar disputam o país, e cidades inteiras ficam cercadas. Sem comida e sem hospitais, milhões de pessoas fogem para os países vizinhos.',
    peso: .7, condicoes: [{ v: 'territorio.africa_oriental.conflito', min: 1, exige: true }, { v: 'global.tensao', min: 75, x: 1.3 }],
    efeitos: [{ v: 'local.estabilidade', d: -6 }, { v: 'local.desenvolvimento', d: -2 }, { v: 'vizinhos.estabilidade', d: -2 }, { v: 'global.deslocados', d: 5 }],
    escolha: { tipo: 'votacao', resolucao: 'fundo_humanitario' },
    manchete: 'Guerra no Sudão provoca uma das maiores crises humanitárias do mundo',
    bncc: ['EM13CHS503', 'EM13CHS605', 'EM13CHS201'],
    vocesabia: 'A guerra no Sudão começou em abril de 2023. No fim de 2025, quase 13 milhões de sudaneses estavam deslocados dentro e fora do país; só dentro do Sudão eram 9,1 milhões, o maior deslocamento interno do mundo (ACNUR, 2026).' },
  { id: 'crise_haiti', titulo: 'Violência de gangues no Haiti', icone: '🚨', tipo: 'conflito', temas: ['conflitos', 'pessoas', 'ordem'], local: 'caribe',
    texto: 'Gangues armadas controlam bairros inteiros de Porto Príncipe, a capital do Haiti. Escolas e hospitais fecham, e centenas de milhares de pessoas deixam suas casas.',
    peso: .7, condicoes: [{ v: 'territorio.caribe.estabilidade', max: 45, exige: true }],
    efeitos: [{ v: 'local.estabilidade', d: -6 }, { v: 'local.desenvolvimento', d: -2 }, { v: 'global.deslocados', d: 2 }],
    escolha: { tipo: 'votacao', resolucao: 'missao_paz' },
    manchete: 'Haiti pede ajuda internacional contra a violência das gangues',
    bncc: ['EM13CHS503', 'EM13CHS604', 'EM13CHS201'],
    vocesabia: 'De 2004 a 2017, o Brasil comandou as tropas da missão de paz da ONU no Haiti, a Minustah. Depois do terremoto de 2010, milhares de haitianos migraram para o Brasil, e muitos foram trabalhar no Sul, sobretudo em Santa Catarina (ONU; OBMigra).' },

  // ---------------- 🧳 MIGRAÇÕES ----------------
  { id: 'operacao_acolhida', titulo: 'Operação Acolhida', icone: '🤝', tipo: 'migracao', temas: ['pessoas', 'territorio'], local: 'brasil',
    texto: 'Milhares de venezuelanos cruzam a fronteira em Pacaraima, em Roraima. O Brasil recebe, documenta e vacina as famílias e leva muitas delas para outros estados, como Santa Catarina.',
    peso: .7, condicoes: [{ v: 'territorio.venezuela_guianas.estabilidade', max: 35, x: 1.5 }, { v: 'global.deslocados', min: 140, x: 1.3 }],
    efeitos: [{ v: 'global.deslocados', d: -3 }, { v: 'global.cooperacao', d: 1 }, { v: 'local.economia', d: -1 }, { v: 'local.economia', d: 2, atraso: 2 }],
    manchete: 'Operação Acolhida leva migrantes venezuelanos de Roraima para todo o Brasil',
    bncc: ['EM13CHS201', 'EM13CHS401', 'EM13CHS502', 'EM13CHS606'],
    vocesabia: 'De 2018 a fevereiro de 2024, a Operação Acolhida levou mais de 128 mil venezuelanos de Roraima para 1.026 municípios, sobretudo da Região Sul. Muitos foram trabalhar em frigoríficos, setor forte em Santa Catarina (Governo Federal).' },
  { id: 'travessias_perigosas', titulo: 'Travessias perigosas', icone: '🛶', tipo: 'migracao', temas: ['pessoas', 'globalizacao'],
    local: { entre: ['norte_africa', 'mexico'] },
    texto: 'Barcos lotados no Mediterrâneo e longas caminhadas no deserto entre o México e os EUA: milhares de pessoas arriscam a vida em busca de segurança e trabalho.',
    peso: .8, condicoes: [{ v: 'global.deslocados', min: 140, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -3 }, { v: 'global.cooperacao', d: -1 }],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Abrir rotas legais: vistos de trabalho e de acolhida humanitária.', resumo: 'Rotas legais', categoria: 'pessoas',
          efeitos: [{ v: 'apoio', d: -1 }, { v: 'global.deslocados', d: -2 }, { v: 'economia', d: 2, atraso: 2 }, { v: 'contadores.solidariedade', d: 1 }],
          porque: 'Com caminho legal, menos gente arrisca a vida nas mãos de traficantes, e quem chega trabalha com documentos.',
          manchete: '{quem} {abre|abrem} vistos de trabalho e de acolhida humanitária' },
        { texto: 'Pagar aos países de trânsito para segurar os migrantes.', resumo: 'Pagar os países de trânsito', categoria: 'diplomacia',
          efeitos: [{ v: 'economia', d: -2 }, { v: 'local.estabilidade', d: 2 }, { v: 'apoio', d: 1 }],
          porque: 'O fluxo diminui na sua fronteira, mas as pessoas ficam presas no caminho, muitas vezes sem direitos.',
          manchete: '{quem} {paga|pagam} países de trânsito para conter migrantes' },
        { texto: 'Endurecer o controle da fronteira.', resumo: 'Endurecer a fronteira', categoria: 'seguranca',
          efeitos: [{ v: 'apoio', d: 2 }, { v: 'global.deslocados', d: 1 }, { v: 'global.cooperacao', d: -1 }],
          porque: 'Muros e patrulhas agradam parte dos eleitores, mas empurram as pessoas para rotas ainda mais perigosas.',
          manchete: '{quem} {endurece|endurecem} a fronteira, e as rotas ficam mais perigosas' },
      ] },
    manchete: 'Travessias perigosas: migrantes arriscam a vida por segurança e trabalho',
    bncc: ['EM13CHS201', 'EM13CHS502', 'EM13CHS605'],
    vocesabia: 'Desde 2014, mais de 86 mil migrantes morreram ou desapareceram nas rotas do mundo, mais de 35 mil deles no Mediterrâneo (OIM, 2026). Em 2022, a fronteira entre EUA e México foi a rota terrestre mais mortal do planeta (OIM).' },

  // ---------------- 💎 RECURSOS ----------------
  { id: 'corrida_litio', titulo: 'Corrida pelo lítio', icone: '🔋', tipo: 'recursos', temas: ['natureza', 'globalizacao'],
    local: { entre: ['andes', 'cone_sul'] },
    texto: 'Empresas de várias potências disputam o lítio dos desertos de sal dos Andes, essencial para baterias de celulares e carros elétricos. Comunidades indígenas temem pela pouca água da região.',
    peso: .8,
    efeitos: [{ v: 'local.recursos.minerais', d: 1 }, { v: 'local.desenvolvimento', d: 2, atraso: 1 }, { v: 'local.pressao', d: 8 }, { v: 'local.estabilidade', d: -2 }],
    manchete: 'Corrida pelo lítio esquenta nos Andes',
    bncc: ['EM13CHS302', 'EM13CHS202', 'EM13CNT309'],
    vocesabia: 'Argentina, Bolívia e Chile, o “Triângulo do Lítio”, reúnem mais de 40% dos recursos de lítio conhecidos no mundo, e 88% do lítio consumido vai para baterias (USGS, 2026).' },
  { id: 'terras_raras', titulo: 'Terras raras na disputa', icone: '🧲', tipo: 'recursos', temas: ['globalizacao', 'natureza'], local: 'china',
    texto: 'A China, maior produtora de terras raras, passa a exigir licença para exportá-las, alegando segurança nacional. Fábricas de celulares e carros elétricos temem ficar sem ímãs; reciclar eletrônicos vira prioridade.',
    peso: .7, condicoes: [{ v: 'global.tensao', min: 75, x: 1.5 }, { v: 'global.comercio', max: 50, x: 1.3 }],
    efeitos: [{ v: 'todos.recursos.minerais', d: -1 }, { v: 'local.recursos.minerais', d: 1 }, { v: 'global.tensao', d: 3 }, { v: 'global.comercio', d: -2 }],
    escolha: { tipo: 'decisao',
      opcoes: [
        { texto: 'Reciclar ímãs e baterias e buscar outros fornecedores.', resumo: 'Reciclar e diversificar', categoria: 'natureza',
          efeitos: [{ v: 'economia', d: -1 }, { v: 'seguranca', d: 1 }, { v: 'recursos.minerais', d: 1, atraso: 1 }],
          porque: 'Diversificar e reciclar custa caro, mas tira o país da mão de um único fornecedor.',
          manchete: '{quem} {recicla|reciclam} ímãs e {busca|buscam} novos fornecedores de terras raras' },
        { texto: 'Negociar as licenças e manter o comércio.', resumo: 'Negociar as licenças', categoria: 'diplomacia',
          efeitos: [{ v: 'global.tensao', d: -1 }, { v: 'seguranca', d: -1 }],
          porque: 'Negociar mantém as fábricas funcionando e baixa a tensão, mas a dependência continua.',
          manchete: '{quem} {negocia|negociam} licenças para seguir comprando terras raras' },
        { texto: 'Responder com restrições às próprias exportações.', resumo: 'Retaliar', categoria: 'economia',
          efeitos: [{ v: 'apoio', d: 1 }, { v: 'global.tensao', d: 2 }, { v: 'global.comercio', d: -2 }],
          porque: 'Retaliar mostra força, mas transforma uma disputa comercial numa guerra de bloqueios em que todos perdem.',
          manchete: '{quem} {retalia|retaliam} com restrições, e a guerra comercial esquenta' },
      ] },
    manchete: 'Restrição às terras raras expõe a dependência das cadeias globais',
    bncc: ['EM13CHS202', 'EM13CHS302', 'EM13CHS301', 'EM13CHS201'],
    vocesabia: 'Em 2025, a China extraiu cerca de 70% das terras raras do mundo. O Brasil tem a segunda maior reserva, mas produziu só cerca de 2 mil toneladas, contra 270 mil da China: ter reserva não é o mesmo que produzir (USGS, 2026).' },
  { id: 'disputa_agua', titulo: 'Disputa pela água de um grande rio', icone: '💧', tipo: 'recursos', temas: ['natureza', 'conflitos', 'territorio'],
    local: { entre: ['norte_africa', 'afeg_paquistao'] },
    texto: 'Uma barragem gigante rio acima reduz a água que chega rio abaixo. Agricultores temem perder a safra e governos vizinhos trocam ameaças, enquanto diplomatas tentam um acordo.',
    peso: .7, condicoes: [{ v: 'global.temperatura', min: 1.7, x: 1.5 }, { v: 'global.tensao', min: 75, x: 1.5 }],
    efeitos: [{ v: 'local.estabilidade', d: -5, escala: 'clima' }, { v: 'local.desenvolvimento', d: -1 }, { v: 'local.conflito', d: 1, chance: .2 },
      { v: 'global.tensao', d: 4 }],
    manchete: 'Barragem rio acima acende disputa pela água rio abaixo',
    bncc: ['EM13CHS204', 'EM13CHS302', 'EM13CHS305'],
    vocesabia: 'Em 2025, a Etiópia inaugurou no Nilo Azul a maior hidrelétrica da África, sob protestos do Egito. No mesmo ano, após um atentado na Caxemira, região disputada, a Índia suspendeu o Tratado das Águas do Indo, de 1960, com o Paquistão. Ainda assim, em rios compartilhados a cooperação é mais comum que a guerra (Banco Mundial; ONU-Água).' },
  { id: 'margem_equatorial', titulo: 'Petróleo na Margem Equatorial', icone: '⛽', tipo: 'recursos', temas: ['natureza', 'globalizacao'], local: 'brasil', unico: true,
    texto: 'Uma sonda encontra petróleo no litoral do Amapá, na Margem Equatorial. Uns comemoram empregos e royalties; outros temem riscos para recifes, mangues e para o clima.',
    peso: .6, condicoes: [{ v: 'global.energia', min: 70, x: 1.5 }],
    efeitos: [{ v: 'local.recursos.energia', d: 2 }, { v: 'local.economia', d: 2, atraso: 1 }, { v: 'local.ambiente', d: -2 }, { v: 'global.energia', d: -2 }],
    manchete: 'Petróleo na Margem Equatorial divide o Brasil entre royalties e riscos ambientais',
    bncc: ['EM13CHS302', 'EM13CHS304', 'EM13CHS305'],
    vocesabia: 'Em 2025, o pré-sal respondeu por cerca de 80% do petróleo produzido no Brasil (ANP). No mesmo ano, o Ibama autorizou a Petrobras a perfurar um poço de pesquisa no Amapá, a 175 km da costa e a 500 km da foz do Amazonas (Ibama).' },

  // ---------------- 🗳️ POLÍTICA ----------------
  { id: 'eleicoes', titulo: 'Eleições mudam o governo', icone: '🗳️', tipo: 'politica', temas: ['ordem', 'pessoas'],
    local: { entre: ['cone_sul', 'andes', 'mexico', 'africa_do_sul', 'sudeste_insular', 'japao_coreia', 'turquia', 'africa_ocidental', 'balcas', 'reino_unido', 'canada', 'australia', 'sul_asia'] },
    texto: 'Milhões de eleitores vão às urnas e escolhem um novo governo. A transição é pacífica, e os novos líderes prometem rever os acordos com as potências estrangeiras.',
    peso: 1,
    efeitos: [{ v: 'local.influencia', d: -1 }, { v: 'local.estabilidade', d: 3 }, { v: 'local.pressao', d: -10 }],
    manchete: 'Eleição pacífica muda o governo e reabre a disputa por influência',
    bncc: ['EM13CHS603', 'EM13CHS602', 'EM13LP23'],
    vocesabia: 'O Brasil usa urnas eletrônicas desde 1996, quando 57 cidades votaram com elas. Em 2000, pela primeira vez, todos os municípios do país votaram eletronicamente (TSE).' },
  { id: 'protestos_democracia', titulo: 'Jovens nas ruas pela democracia', icone: '📣', tipo: 'politica', temas: ['pessoas', 'ordem'],
    local: { entre: ['sul_asia', 'africa_oriental', 'sudeste_continental', 'balcas', 'turquia', 'ira', 'asia_central', 'africa_ocidental', 'andes', 'levante', 'leste_europeu', 'norte_africa'], estabilidadeMax: 60 },
    texto: 'Convocados pelas redes sociais, estudantes ocupam as praças contra a corrupção e a censura. O governo precisa escolher entre o diálogo e a repressão.',
    peso: .8,
    efeitos: [{ v: 'local.estabilidade', d: -5 }, { v: 'local.estabilidade', d: 8, atraso: 1, chance: .5 }],
    manchete: 'Protestos liderados por jovens cobram democracia e o fim da corrupção',
    bncc: ['EM13CHS602', 'EM13CHS205', 'EM13CHS404', 'EM13CHS605'],
    vocesabia: 'Em 2024 e 2025, protestos liderados por estudantes e jovens da “Geração Z”, organizados pelas redes sociais, levaram à renúncia dos chefes de governo de Bangladesh e do Nepal (BBC; Al Jazeera).' },
  { id: 'onda_populista', titulo: 'Onda populista', icone: '🎤', tipo: 'politica', temas: ['ordem', 'pessoas'], local: null,
    texto: 'Em vários países, líderes ganham votos dizendo falar pelo “povo verdadeiro” contra as “elites” e prometendo soluções rápidas. Apoiadores se sentem ouvidos; críticos temem ataques a tribunais e à imprensa.',
    peso: .7, condicoes: [{ v: 'global.deslocados', min: 140, x: 1.5 }, { v: 'global.comercio', max: 45, x: 1.3 }],
    efeitos: [{ v: 'global.cooperacao', d: -3 }, { v: 'global.tensao', d: 2 }, { v: 'territorios.pressao', d: 5 }],
    manchete: 'Discursos populistas ganham força e desafiam a cooperação internacional',
    bncc: ['EM13CHS602', 'EM13CHS603', 'EM13CHS101', 'EM13LGG202'],
    vocesabia: 'Para o cientista político Cas Mudde (2004), o populismo divide a sociedade entre um “povo puro” e uma “elite corrupta”. Como essa ideia se junta a outras, ele aparece tanto na esquerda quanto na direita.' },
  { id: 'povos_tradicionais', titulo: 'Indígenas e quilombolas na cúpula do clima', icone: '🏞️', tipo: 'politica', temas: ['pessoas', 'natureza'], local: 'brasil',
    texto: 'Lideranças indígenas e quilombolas levam ao mundo uma mensagem: territórios demarcados e titulados protegem a floresta, a água e modos de vida tradicionais. Elas pedem voz nas decisões sobre o clima.',
    peso: .7, condicoes: [{ v: 'global.cooperacao', min: 55, x: 1.5 }, { v: 'global.temperatura', min: 1.6, x: 1.3 }],
    efeitos: [{ v: 'global.cooperacao', d: 3 }, { v: 'local.ambiente', d: 2 }],
    escolha: { tipo: 'votacao', resolucao: 'acordo_climatico' },
    manchete: 'Povos indígenas e quilombolas pedem terra demarcada como solução para o clima',
    bncc: ['EM13CHS601', 'EM13CHS104', 'EM13CHS105', 'EM13CHS305'],
    vocesabia: 'O Censo 2022 foi o primeiro a contar os quilombolas: cerca de 1,3 milhão de pessoas, além de cerca de 1,7 milhão de indígenas (IBGE). Em 2023, num caso do povo Xokleng, de Santa Catarina, o STF rejeitou a tese do marco temporal; no mesmo ano, o Congresso aprovou uma lei que a adota, e o debate continua (STF; Senado).' },
  { id: 'assembleia_onu', titulo: 'Assembleia Geral da ONU', icone: '🏛️', tipo: 'politica', temas: ['ordem'], local: null,
    texto: 'Líderes dos 193 países-membros discursam em Nova York. Como manda a tradição, o Brasil abre o debate. Na pauta, um fundo comum para vítimas de guerras e desastres.',
    peso: .8, condicoes: [{ v: 'global.deslocados', min: 140, x: 1.5 }],
    efeitos: [{ v: 'global.cooperacao', d: 2 }],
    escolha: { tipo: 'votacao', resolucao: 'fundo_humanitario' },
    manchete: 'Na Assembleia Geral, países debatem um fundo para vítimas de guerras e desastres',
    bncc: ['EM13CHS604', 'EM13CHS603'],
    vocesabia: 'Por uma tradição que não está escrita em regra nenhuma, o Brasil faz o primeiro discurso do debate geral da ONU há mais de 70 anos. Em 1947, o brasileiro Oswaldo Aranha presidiu a Assembleia Geral (ONU).' },

  // ---------------- 🕊️ BOAS NOTÍCIAS ----------------
  { id: 'acordo_paz', titulo: 'Acordo de paz histórico', icone: '🕊️', tipo: 'positivo', temas: ['conflitos', 'ordem'],
    local: { conflitoMin: 1 },
    texto: 'Primeiro veio o cessar-fogo; agora, as partes assinam um acordo de paz, com plano de reconstrução e volta segura de quem fugiu.',
    peso: .6, condicoes: [{ v: 'global.cooperacao', min: 55, x: 2 }, { v: 'global.tensao', max: 65, x: 1.5 }],
    efeitos: [{ v: 'local.conflito', d: -1 }, { v: 'local.estabilidade', d: 10 }, { v: 'global.tensao', d: -5 }, { v: 'global.deslocados', d: -6 }],
    manchete: 'Acordo de paz histórico traz esperança de reconstrução',
    bncc: ['EM13CHS503', 'EM13CHS604', 'EM13CHS501'],
    vocesabia: 'Estudos citados pela ONU Mulheres mostram que acordos de paz assinados também por mulheres são mais cumpridos e duram mais (ONU Mulheres).' },
  { id: 'recorde_solar', titulo: 'Energia solar bate recorde', icone: '☀️', tipo: 'positivo', temas: ['natureza', 'globalizacao'], local: null,
    texto: 'Painéis solares ficam mais baratos do que nunca e superam o carvão em vários países.',
    peso: .7, condicoes: [{ v: 'global.cooperacao', min: 50, x: 1.5 }],
    efeitos: [{ v: 'todos.limpa', d: 3 }, { v: 'global.energia', d: -3 }],
    manchete: 'Energia solar mais barata acelera a transição',
    bncc: ['EM13CHS304', 'EM13CHS306', 'EM13CNT309'],
    vocesabia: 'Em 2025, o mundo instalou um recorde de 692 gigawatts de energia renovável, e sol e vento foram quase 97% desse total. As renováveis já são 49,4% de toda a capacidade elétrica instalada no planeta (IRENA, 2026).' },
  { id: 'vacina_compartilhada', titulo: 'Vacina nova e compartilhada', icone: '💉', tipo: 'positivo', temas: ['pessoas', 'globalizacao'], local: null, unico: true, rodadaMin: 2,
    texto: 'Cientistas de vários países criam em tempo recorde uma vacina contra uma doença que ameaçava virar pandemia. A fórmula é compartilhada, e fábricas do Sul Global começam a produzi-la.',
    peso: .5, condicoes: [{ v: 'global.cooperacao', min: 55, x: 2 }],
    efeitos: [{ v: 'todos.imune.pandemia', d: 2 }, { v: 'territorios.desenvolvimento', d: 1 }, { v: 'global.cooperacao', d: 3 }, { v: 'global.transferencia', d: .05 }],
    manchete: 'Ciência em tempo recorde: vacina nova é compartilhada com o mundo',
    bncc: ['EM13CHS604', 'EM13CHS403', 'EM13CHS504', 'EM13CNT310'],
    vocesabia: 'Entre 2021 e 2023, a iniciativa Covax entregou quase 2 bilhões de doses de vacina contra a covid-19 a 146 países e territórios, cerca de 90% delas para os de renda mais baixa (Gavi).' },
  { id: 'olimpiada', titulo: 'Olimpíada une o planeta', icone: '🏅', tipo: 'positivo', temas: ['pessoas', 'ordem'], local: null,
    texto: 'Atletas de mais de 200 delegações desfilam juntos na abertura dos Jogos. Torcidas rivais se misturam nas arquibancadas, e a ONU pede uma trégua olímpica.',
    peso: .6, condicoes: [{ v: 'global.cooperacao', min: 50, x: 1.5 }, { v: 'global.tensao', max: 70, x: 1.3 }],
    efeitos: [{ v: 'global.tensao', d: -3 }, { v: 'global.cooperacao', d: 2 }, { v: 'todos.apoio', d: 1 }],
    manchete: 'Olimpíada reúne o mundo e a ONU pede trégua durante os Jogos',
    bncc: ['EM13CHS604', 'EM13CHS303', 'EM13CHS502'],
    vocesabia: 'Desde 1993, antes de cada Olimpíada, a Assembleia Geral da ONU aprova uma resolução pela trégua olímpica, de uma semana antes da abertura até uma semana depois da Paralimpíada. Em 2016, o Rio de Janeiro sediou os primeiros Jogos da América do Sul (COI).' },
  { id: 'acordo_comercial', titulo: 'Acordo comercial histórico', icone: '📈', tipo: 'positivo', temas: ['globalizacao', 'ordem'], local: null,
    texto: 'Dois grandes blocos econômicos assinam um acordo de livre-comércio depois de anos de negociação. Tarifas caem; exportadores comemoram, e alguns produtores temem a concorrência.',
    peso: .6, condicoes: [{ v: 'global.cooperacao', min: 50, x: 1.5 }],
    efeitos: [{ v: 'global.comercio', d: 4 }, { v: 'todos.economia', d: 1 }, { v: 'global.cooperacao', d: 2 }, { v: 'global.tensao', d: -1 }],
    manchete: 'Blocos econômicos assinam acordo de livre-comércio histórico',
    bncc: ['EM13CHS201', 'EM13CHS604', 'EM13CHS402'],
    vocesabia: 'Depois de mais de 25 anos de negociação, Mercosul e União Europeia assinaram em janeiro de 2026 um acordo de livre-comércio que reúne mais de 700 milhões de pessoas. Desde maio de 2026, a parte comercial vale de forma provisória, enquanto a aprovação final segue em debate na Europa (Comissão Europeia; Agência Senado).' },
];
