// =====================================================================
//  GEOGRAFIA IRADA — cartas de política (as decisões das potências)
// =====================================================================
//  Cada carta é só dado: o motor (js/simulacao.js) aplica os efeitos. Campos:
//   custo: cp (Capital Político) e, se houver, economia (pontos de 💰), alimentos, energia, minerais, tecnologia
//   alvo:  'nenhum' | 'territorio' | 'potencia' | 'territorios3' (escolhe até 3 territórios)
//   requisito: condições do alvo (conflitoMin, conflitoMax, estabilidadeMax, desenvolvimentoMax, produz)
//   efeitos: lista de { v: caminho, d: soma } ou { v: caminho, m: multiplica }, com atraso (balanços) opcional
//   caminhos: 'economia' (a própria potência) · 'recursos.energia' · 'producao.tecnologia' · 'global.tensao'
//             'alvo.estabilidade' · 'influencia' (sua influência no alvo) · 'todos.economia' (todas as potências)
//             'vizinhos.estabilidade' (vizinhos do alvo) · 'vizinhosCasa.influencia' · 'territorios.vulnerabilidade'
//             'emConflito.influencia' · 'comFloresta.floresta' · 'vulneraveis.influencia' (os 3 mais vulneráveis)
//   extra:   efeitos a mais para uma potência (a habilidade especial dela)
//   desconto: CP a menos para uma potência
//   porque:  a frase de causa e efeito que aparece na tela
// =====================================================================

const CATEGORIAS = {
  diplomacia: { nome: 'Diplomacia', cor: '#9B5CF6', icone: '🤝' },
  economia:   { nome: 'Economia e Comércio', cor: '#FF9F1C', icone: '💰' },
  natureza:   { nome: 'Natureza e Energia', cor: '#22B14C', icone: '🌱' },
  seguranca:  { nome: 'Paz e Segurança', cor: '#EF3B3B', icone: '🛡️' },
  pessoas:    { nome: 'Pessoas e Direitos', cor: '#F25CA2', icone: '👥' },
  ciencia:    { nome: 'Ciência e Informação', cor: '#2F80ED', icone: '💡' },
};

const POLITICAS = [
  // ---------------- 🤝 DIPLOMACIA ----------------
  { id: 'missao_diplomatica', fixa: true, nome: 'Missão diplomática', categoria: 'diplomacia', icone: '🧳',
    custo: { cp: 1 }, alvo: 'territorio',
    efeitos: [{ v: 'influencia', d: 2 }, { v: 'global.cooperacao', d: 1 }],
    porque: 'Embaixadas, visitas oficiais e acordos de cooperação aproximam governos e povos.',
    conceito: 'Diplomacia e política externa', bncc: ['EM13CHS603', 'EM13CHS604'] },
  { id: 'cooperacao_sul_sul', nome: 'Cooperação Sul-Sul', categoria: 'diplomacia', icone: '🌍',
    custo: { cp: 2, tecnologia: 1 }, alvo: 'territorio', requisito: { desenvolvimentoMax: 70 },
    efeitos: [{ v: 'influencia', d: 3 }, { v: 'alvo.desenvolvimento', d: 6, atraso: 1 }, { v: 'global.cooperacao', d: 1 }],
    porque: 'Países em desenvolvimento trocam técnicas de saúde, agricultura e educação que já deram certo em realidades parecidas.',
    conceito: 'Cooperação Sul-Sul e Sul Global', bncc: ['EM13CHS102', 'EM13CHS604'] },
  { id: 'propor_resolucao', nome: 'Propor resolução na ONU', categoria: 'diplomacia', icone: '🏛️',
    custo: { cp: 2 }, alvo: 'nenhum', especial: 'votacao', efeitos: [],
    porque: 'Na ONU, problemas que nenhum país resolve sozinho são decididos em votação, e cinco países têm poder de veto no Conselho de Segurança.',
    conceito: 'Organismos internacionais', bncc: ['EM13CHS604', 'EM13CHS603'] },
  { id: 'sancoes', nome: 'Sanções econômicas', categoria: 'diplomacia', icone: '⛔',
    custo: { cp: 2 }, alvo: 'potencia',
    efeitos: [{ v: 'alvo.economia', d: -5 }, { v: 'economia', d: -1 }, { v: 'global.comercio', d: -3 },
      { v: 'global.tensao', d: 4 }, { v: 'global.cooperacao', d: -2 }],
    extra: { eua: [{ v: 'alvo.economia', d: -2 }] },
    especial: 'sancao',
    porque: 'Sanções cortam comércio e crédito para pressionar um governo, mas também custam caro a quem sanciona e esquentam a disputa.',
    conceito: 'Sanções e poder econômico', bncc: ['EM13CHS604', 'EM13CHS201'] },
  { id: 'alianca', nome: 'Aliança estratégica', categoria: 'diplomacia', icone: '🤜',
    custo: { cp: 2 }, alvo: 'potencia', especial: 'alianca',
    efeitos: [{ v: 'seguranca', d: 4 }, { v: 'alvo.seguranca', d: 4 }, { v: 'global.tensao', d: 2 }],
    extra: { india: [{ v: 'global.tensao', d: -2 }] },
    porque: 'Alianças dão segurança a quem participa, mas quem fica de fora pode se sentir ameaçado: é o dilema de segurança.',
    conceito: 'Alianças e blocos militares (ex.: OTAN)', bncc: ['EM13CHS603', 'EM13CHS204'] },
  { id: 'cupula_regional', nome: 'Cúpula regional', categoria: 'diplomacia', icone: '🎙️',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'vizinhosCasa.influencia', d: 1 }, { v: 'apoio', d: 1 }],
    porque: 'Encontros de presidentes vizinhos (como os do Mercosul ou da União Africana) fortalecem laços na própria região.',
    conceito: 'Integração regional', bncc: ['EM13CHS201', 'EM13CHS204'] },

  // ---------------- 💰 ECONOMIA E COMÉRCIO ----------------
  { id: 'livre_comercio', nome: 'Acordo de livre-comércio', categoria: 'economia', icone: '🚢',
    custo: { cp: 2 }, alvo: 'territorio',
    efeitos: [{ v: 'global.comercio', d: 3 }, { v: 'economia', d: 2 }, { v: 'alvo.desenvolvimento', d: 2 }, { v: 'influencia', d: 2 }],
    extra: { eua: [{ v: 'economia', d: 1 }], ue: [{ v: 'global.cooperacao', d: 1 }] },
    porque: 'Sem tarifas, os dois lados vendem mais um para o outro e cada um se especializa no que faz melhor.',
    conceito: 'Blocos econômicos e vantagem comparativa', bncc: ['EM13CHS201', 'EM13CHS202'] },
  { id: 'tarifas', nome: 'Tarifas de importação', categoria: 'economia', icone: '🧱',
    custo: { cp: 1 }, alvo: 'potencia',
    efeitos: [{ v: 'economia', d: 1 }, { v: 'economia', d: -1, atraso: 1 }, { v: 'alvo.economia', d: -3 },
      { v: 'global.comercio', d: -4 }, { v: 'global.tensao', d: 3 }, { v: 'apoio', d: 2 }],
    porque: 'Taxar importados protege a indústria nacional por um tempo, mas encarece produtos, provoca retaliação e encolhe o comércio mundial.',
    conceito: 'Protecionismo e guerra comercial', bncc: ['EM13CHS201', 'EM13CHS402'] },
  { id: 'infraestrutura_exterior', nome: 'Infraestrutura no exterior', categoria: 'economia', icone: '🏗️',
    custo: { cp: 3, minerais: 1 }, alvo: 'territorio', desconto: { china: 1 },
    efeitos: [{ v: 'influencia', d: 4 }, { v: 'alvo.desenvolvimento', d: 6, atraso: 1 }, { v: 'alvo.pressao', d: 10 }],
    porque: 'Portos, ferrovias e usinas financiados de fora geram desenvolvimento, mas também dívida e dependência.',
    conceito: 'Investimento externo (ex.: Nova Rota da Seda)', bncc: ['EM13CHS201', 'EM13CHS204'] },
  { id: 'exportar_commodities', nome: 'Exportar commodities', categoria: 'economia', icone: '🌽',
    custo: { cp: 1 }, alvo: 'nenhum', especial: 'commodities',
    efeitos: [{ v: 'economia', d: 3 }],
    porque: 'Vender grãos e minérios traz dinheiro rápido, mas deixa a economia dependente do preço internacional.',
    conceito: 'Commodities e divisão internacional do trabalho', bncc: ['EM13CHS302', 'EM13CHS201'] },
  { id: 'politica_industrial', nome: 'Política industrial', categoria: 'economia', icone: '🏭',
    custo: { cp: 2, energia: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'economia', d: 4, atraso: 1 }, { v: 'producao.tecnologia', d: 1 }, { v: 'fossil', m: 1.08 }],
    porque: 'Fábricas novas geram empregos e tecnologia, mas consomem energia e, se ela for fóssil, aumentam as emissões.',
    conceito: 'Industrialização', bncc: ['EM13CHS401', 'EM13CHS403'] },
  { id: 'transnacionais', nome: 'Atrair empresas transnacionais', categoria: 'economia', icone: '🏢',
    custo: { cp: 1 }, alvo: 'nenhum', especial: 'transnacionais',
    efeitos: [{ v: 'economia', d: 2 }, { v: 'global.comercio', d: 1 }],
    porque: 'Multinacionais trazem investimento e empregos, mas buscam custos baixos: os empregos podem ser precários se a renda for baixa.',
    conceito: 'Empresas transnacionais e globalização', bncc: ['EM13CHS401', 'EM13CHS402'] },
  { id: 'emprestimo', nome: 'Empréstimo a país em crise', categoria: 'economia', icone: '🏦',
    custo: { cp: 2, economia: 2 }, alvo: 'territorio', requisito: { estabilidadeMax: 45 },
    efeitos: [{ v: 'alvo.estabilidade', d: 8 }, { v: 'influencia', d: 3 }, { v: 'alvo.desenvolvimento', d: -2 }],
    porque: 'O empréstimo evita o calote, mas costuma vir com cortes de gastos que pesam sobre a população.',
    conceito: 'Dívida externa e instituições financeiras (FMI, Banco Mundial)', bncc: ['EM13CHS604', 'EM13CHS402'] },

  // ---------------- 🌱 NATUREZA E ENERGIA ----------------
  { id: 'energia_renovavel', nome: 'Energia renovável', categoria: 'natureza', icone: '☀️',
    custo: { cp: 2, minerais: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'limpa', d: 10 }, { v: 'economia', d: -1 }, { v: 'producao.energia', d: 1, atraso: 1 }, { v: 'global.energia', d: -1 }],
    porque: 'Sol e vento substituem carvão e petróleo: a matriz fica mais limpa e as emissões caem. Mas painéis e baterias precisam de minerais críticos.',
    conceito: 'Transição energética', bncc: ['EM13CHS304', 'EM13CHS306', 'EM13CNT309'] },
  { id: 'explorar_petroleo', nome: 'Explorar petróleo e gás', categoria: 'natureza', icone: '🛢️',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'recursos.energia', d: 2 }, { v: 'economia', d: 2 }, { v: 'limpa', d: -4 }, { v: 'fossil', m: 1.06 }, { v: 'ambiente', d: -2 },
      { v: 'global.energia', d: -3 }],
    porque: 'Mais petróleo e gás barateiam a energia e dão lucro agora, mas prendem o país a combustíveis que aquecem o planeta.',
    conceito: 'Geopolítica do petróleo', bncc: ['EM13CHS302', 'EM13CNT309'] },
  { id: 'desmatamento_zero', nome: 'Desmatamento zero', categoria: 'natureza', icone: '🌳',
    custo: { cp: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'desmatamento', m: .5 }, { v: 'ambiente', d: 5 }, { v: 'economia', d: -1 }, { v: 'global.cooperacao', d: 2 }],
    extra: { brasil: [{ v: 'global.temperatura', d: -.02 }, { v: 'ambiente', d: 2 }] },
    porque: 'Floresta em pé guarda carbono, protege a chuva e a biodiversidade. O agro perde um pouco de área para crescer.',
    conceito: 'Florestas e clima', bncc: ['EM13CHS302', 'EM13CHS306', 'EM13CNT206'] },
  { id: 'fronteira_agricola', nome: 'Expandir a fronteira agrícola', categoria: 'natureza', icone: '🚜',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'recursos.alimentos', d: 2 }, { v: 'economia', d: 2 }, { v: 'ambiente', d: -4 }, { v: 'desmatamento', d: .2 }],
    porque: 'Abrir novas áreas de plantio aumenta a produção, mas derruba vegetação nativa e libera carbono.',
    conceito: 'Agronegócio e impactos socioambientais', bncc: ['EM13CHS302', 'EM13CHS306'] },
  { id: 'fundo_climatico', nome: 'Fundo climático internacional', categoria: 'natureza', icone: '💧',
    custo: { cp: 2, economia: 3 }, alvo: 'nenhum',
    efeitos: [{ v: 'global.cooperacao', d: 3 }, { v: 'territorios.vulnerabilidade', d: -5 }, { v: 'vulneraveis.influencia', d: 1 },
      { v: 'global.transferencia', d: .1 }],
    porque: 'Os países que mais emitiram ajudam os mais vulneráveis a se adaptar e a crescer sem carvão.',
    conceito: 'Justiça climática e financiamento', bncc: ['EM13CHS305', 'EM13CHS306'] },
  { id: 'florestas_tropicais', nome: 'Fundo para florestas tropicais', categoria: 'natureza', icone: '🦜',
    custo: { cp: 2, economia: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'comFloresta.floresta', m: .7 }, { v: 'comFloresta.influencia', d: 1 }, { v: 'global.cooperacao', d: 2 }],
    porque: 'Pagar para manter florestas em pé recompensa quem protege e torna a floresta mais valiosa viva do que derrubada.',
    conceito: 'Pagamento por serviços ambientais', bncc: ['EM13CHS306', 'EM13CHS305'] },
  { id: 'meta_climatica', nome: 'Meta climática ambiciosa', categoria: 'natureza', icone: '🎯',
    custo: { cp: 1 }, alvo: 'nenhum', especial: 'meta_ndc', efeitos: [],
    porque: 'No Acordo de Paris, cada país promete quanto vai cortar (a NDC). Cumprir dá credibilidade; descumprir desgasta.',
    conceito: 'Acordo de Paris e NDCs', bncc: ['EM13CHS305'] },
  { id: 'minerais_criticos', nome: 'Minerais críticos', categoria: 'natureza', icone: '🔋',
    custo: { cp: 1 }, alvo: 'territorio', especial: 'minerais', requisito: { produz: 'minerais', ouCasa: true },
    efeitos: [{ v: 'recursos.minerais', d: 2 }, { v: 'economia', d: 2 }],
    porque: 'Lítio, cobalto e terras raras movem baterias e chips. Quem controla essas minas ganha poder, mas a mineração tem custos locais.',
    conceito: 'Geopolítica dos minerais críticos', bncc: ['EM13CHS302', 'EM13CNT309'] },
  { id: 'nuclear', nome: 'Energia nuclear', categoria: 'natureza', icone: '⚛️',
    custo: { cp: 2, tecnologia: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'limpa', d: 8 }, { v: 'producao.energia', d: 1, atraso: 1 }, { v: 'global.tensao', d: 1 }],
    porque: 'Usinas nucleares geram muita energia sem CO₂, mas exigem segurança e controle internacional do urânio.',
    conceito: 'Energia nuclear para fins pacíficos', bncc: ['EM13CNT103', 'EM13CHS304'] },
  { id: 'adaptacao', nome: 'Adaptação climática', categoria: 'natureza', icone: '🌊',
    custo: { cp: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'vulnerabilidade', d: -15 }, { v: 'bemEstar', d: 2 }],
    porque: 'Diques, cisternas, cidades mais verdes e alertas de desastre diminuem o estrago de secas, cheias e ondas de calor.',
    conceito: 'Adaptação e vulnerabilidade', bncc: ['EM13CHS306', 'EM13CNT310'] },

  // ---------------- 🛡️ PAZ E SEGURANÇA ----------------
  { id: 'defesa', nome: 'Ampliar a defesa', categoria: 'seguranca', icone: '🛡️',
    custo: { cp: 2, economia: 2 }, alvo: 'nenhum', especial: 'defesa',
    efeitos: [{ v: 'militar', d: 12 }, { v: 'seguranca', d: 5 }, { v: 'global.tensao', d: 4 }],
    porque: 'Gastar mais com defesa dá segurança, mas os vizinhos se sentem ameaçados e também se armam: é o dilema de segurança.',
    conceito: 'Dilema de segurança e corrida armamentista', bncc: ['EM13CHS603', 'EM13CHS504'] },
  { id: 'ciberdefesa', nome: 'Ciberdefesa', categoria: 'seguranca', icone: '🔐',
    custo: { cp: 1, tecnologia: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'seguranca', d: 2 }, { v: 'imune.ciber', d: 2 }],
    porque: 'Hospitais, bancos e redes de energia dependem da internet; proteger esses sistemas é segurança nacional.',
    conceito: 'Ciberespaço e soberania digital', bncc: ['EM13CHS202', 'EM13CHS504'] },
  { id: 'mediacao', nome: 'Mediação de paz', categoria: 'seguranca', icone: '🕊️',
    custo: { cp: 2 }, alvo: 'territorio', requisito: { conflitoMin: 1 }, especial: 'mediacao',
    efeitos: [],
    // a chance de dar certo vem de Simulacao.chanceMediacao (influência, cooperação, estabilidade, intensidade, ser parte)
    seSucesso: [{ v: 'alvo.conflito', d: -1 }, { v: 'global.tensao', d: -5 }, { v: 'influencia', d: 2 }, { v: 'apoio', d: 3 }],
    seFracasso: [{ v: 'global.tensao', d: -1 }, { v: 'influencia', d: 1 }],
    porque: 'Um mediador precisa da confiança dos dois lados: influência no lugar, um mundo cooperativo e não ser parte da briga. Força não basta, e cessar-fogo não é garantido.',
    conceito: 'Resolução pacífica de conflitos', bncc: ['EM13CHS503', 'EM13CHS604'] },
  { id: 'reconstrucao', nome: 'Ajuda à reconstrução', categoria: 'seguranca', icone: '🧰',
    custo: { cp: 2, economia: 2 }, alvo: 'territorio', requisito: { conflitoMax: 1, estabilidadeMax: 60 },
    efeitos: [{ v: 'alvo.estabilidade', d: 10 }, { v: 'alvo.desenvolvimento', d: 5 }, { v: 'global.deslocados', d: -5 }, { v: 'influencia', d: 3 }],
    porque: 'Reconstruir escolas, hospitais e estradas depois de um conflito permite que as pessoas voltem para casa.',
    conceito: 'Reconstrução pós-conflito', bncc: ['EM13CHS503', 'EM13CHS605'] },
  { id: 'base_militar', nome: 'Base militar no exterior', categoria: 'seguranca', icone: '⚓',
    custo: { cp: 2 }, alvo: 'territorio',
    efeitos: [{ v: 'influencia', d: 3 }, { v: 'seguranca', d: 2 }, { v: 'global.tensao', d: 3 }, { v: 'alvo.pressao', d: 15 }],
    porque: 'Bases dão presença e influência, mas muita gente no país anfitrião vê isso como interferência na soberania.',
    conceito: 'Soberania e projeção de poder', bncc: ['EM13CHS204', 'EM13CHS603'] },
  { id: 'crime_transnacional', nome: 'Combate ao crime transnacional', categoria: 'seguranca', icone: '🚔',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'seguranca', d: 2 }, { v: 'vizinhosCasa.estabilidade', d: 3 }, { v: 'global.cooperacao', d: 1 }],
    porque: 'Tráfico de drogas, armas e pessoas atravessa fronteiras: só a cooperação entre polícias e países consegue enfrentá-lo.',
    conceito: 'Crime organizado transnacional', bncc: ['EM13CHS503', 'EM13CHS204'] },
  { id: 'desarmamento', nome: 'Desarmamento', categoria: 'seguranca', icone: '🕊️',
    custo: { cp: 2 }, alvo: 'nenhum', especial: 'desarmamento',
    efeitos: [{ v: 'militar', d: -15 }, { v: 'global.tensao', d: -6 }, { v: 'global.cooperacao', d: 3 }, { v: 'seguranca', d: -2 }],
    porque: 'Quando um país reduz armas e é verificado, os outros relaxam; quando vários fazem juntos, a tensão cai muito mais.',
    conceito: 'Tratados de desarmamento e não proliferação', bncc: ['EM13CHS604', 'EM13CHS504'] },

  // ---------------- 👥 PESSOAS E DIREITOS ----------------
  { id: 'acolher_refugiados', nome: 'Acolher refugiados', categoria: 'pessoas', icone: '🏠',
    custo: { cp: 1, alimentos: 1 }, alvo: 'nenhum', especial: 'acolher',
    efeitos: [{ v: 'global.deslocados', d: -6 }, { v: 'bemEstar', d: -1 }, { v: 'apoio', d: -2 }, { v: 'economia', d: 2, atraso: 2 },
      { v: 'emConflito.influencia', d: 1, max: 2 }],
    porque: 'Acolher custa no começo e gera debate, mas refugiados integrados trabalham, estudam e fortalecem a economia.',
    conceito: 'Refugiados e direito de asilo', bncc: ['EM13CHS201', 'EM13CHS605'] },
  { id: 'ajuda_humanitaria', nome: 'Ajuda humanitária', categoria: 'pessoas', icone: '📦',
    custo: { cp: 2, alimentos: 2 }, alvo: 'territorio',
    efeitos: [{ v: 'global.deslocados', d: -8 }, { v: 'alvo.estabilidade', d: 5 }, { v: 'influencia', d: 2 }],
    porque: 'Comida, água, remédios e abrigo salvam vidas em guerras e desastres e evitam que mais gente precise fugir.',
    conceito: 'Ajuda humanitária e direitos humanos', bncc: ['EM13CHS605', 'EM13CHS503'] },
  { id: 'educacao', nome: 'Investir em educação', categoria: 'pessoas', icone: '🎓',
    custo: { cp: 2, economia: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'bemEstar', d: 6, atraso: 1 }, { v: 'producao.tecnologia', d: 1, atraso: 2 }],
    porque: 'Educação demora para dar resultado, mas é o que mais aumenta o desenvolvimento humano e a capacidade de inovar.',
    conceito: 'Desenvolvimento humano (IDH)', bncc: ['EM13CHS606', 'EM13CHS402'] },
  { id: 'saude', nome: 'Saúde pública e vacinas', categoria: 'pessoas', icone: '💉',
    custo: { cp: 2, economia: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'bemEstar', d: 5 }, { v: 'imune.pandemia', d: 3 }],
    porque: 'Um sistema de saúde forte e vacinas aumentam a expectativa de vida e seguram epidemias.',
    conceito: 'Saúde global', bncc: ['EM13CHS606', 'EM13CNT310'] },
  { id: 'combate_fome', nome: 'Combate à fome e à desigualdade', categoria: 'pessoas', icone: '🍲',
    custo: { cp: 2, economia: 1, alimentos: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'bemEstar', d: 4 }, { v: 'apoio', d: 3 }],
    extra: { brasil: [{ v: 'bemEstar', d: 2 }] },
    porque: 'Transferência de renda e merenda escolar tiram famílias da fome e fazem a economia girar.',
    conceito: 'Desigualdade e políticas públicas', bncc: ['EM13CHS606', 'EM13CHS402'] },
  { id: 'povos_originarios', nome: 'Direitos de indígenas e quilombolas', categoria: 'pessoas', icone: '🪶',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'ambiente', d: 3 }, { v: 'bemEstar', d: 2 }, { v: 'desmatamento', d: -.1 }],
    porque: 'Terras indígenas e quilombolas demarcadas estão entre as áreas mais preservadas: garantir esses direitos também protege a natureza.',
    conceito: 'Territorialidades indígenas e quilombolas', bncc: ['EM13CHS601', 'EM13CHS302'] },
  { id: 'fechar_fronteiras', nome: 'Fechar fronteiras', categoria: 'pessoas', icone: '🚧',
    custo: { cp: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'apoio', d: 3 }, { v: 'global.deslocados', d: 4 }, { v: 'emConflito.influencia', d: -2 }, { v: 'economia', d: -1, atraso: 1 },
      { v: 'global.cooperacao', d: -2 }],
    porque: 'Fechar fronteiras agrada parte dos eleitores, mas não acaba com as guerras que fazem as pessoas fugirem: a crise só muda de lugar.',
    conceito: 'Migrações, fronteiras e xenofobia', bncc: ['EM13CHS201', 'EM13CHS502'] },

  // ---------------- 💡 CIÊNCIA E INFORMAÇÃO ----------------
  { id: 'pesquisa', nome: 'Pesquisa e inovação', categoria: 'ciencia', icone: '🔬',
    custo: { cp: 2, economia: 2 }, alvo: 'nenhum',
    efeitos: [{ v: 'producao.tecnologia', d: 2, atraso: 1 }, { v: 'economia', d: 3, atraso: 2 }],
    porque: 'Universidades e laboratórios criam vacinas, chips e energia limpa: quem inova depende menos dos outros.',
    conceito: 'Ciência, tecnologia e poder', bncc: ['EM13CHS202', 'EM13CHS401'] },
  { id: 'combate_desinformacao', nome: 'Combate à desinformação', categoria: 'ciencia', icone: '📰',
    custo: { cp: 1, tecnologia: 1 }, alvo: 'nenhum',
    efeitos: [{ v: 'apoio', d: 2 }, { v: 'imune.desinfo', d: 2 }],
    porque: 'Educação midiática e checagem de fatos reduzem o poder das notícias falsas sobre as eleições e a saúde.',
    conceito: 'Desinformação e cidadania digital', bncc: ['EM13CHS202', 'EM13LP40'] },
  { id: 'programa_espacial', nome: 'Programa espacial e satélites', categoria: 'ciencia', icone: '🛰️',
    custo: { cp: 3, tecnologia: 2 }, alvo: 'territorios3',
    efeitos: [{ v: 'seguranca', d: 2 }, { v: 'influencia', d: 1 }, { v: 'apoio', d: 2 }],
    porque: 'Satélites monitoram florestas, safras e desastres e conectam regiões isoladas, e dados de satélite podem ser compartilhados com outros países.',
    conceito: 'Geotecnologias e espaço', bncc: ['EM13CHS106', 'EM13CHS202'] },
  { id: 'soft_power', nome: 'Diplomacia cultural', categoria: 'ciencia', icone: '🎬',
    custo: { cp: 1 }, alvo: 'territorios3',
    efeitos: [{ v: 'influencia', d: 1 }],
    porque: 'Música, cinema, futebol, novelas e games fazem o mundo admirar um país: é o "poder brando" (soft power).',
    conceito: 'Soft power e globalização cultural', bncc: ['EM13CHS303', 'EM13CHS205'] },
  { id: 'internet_para_todos', nome: 'Internet e cabos submarinos', categoria: 'ciencia', icone: '🌐',
    custo: { cp: 2, tecnologia: 1 }, alvo: 'territorio',
    efeitos: [{ v: 'influencia', d: 2 }, { v: 'alvo.desenvolvimento', d: 4 }, { v: 'global.comercio', d: 1 }],
    porque: 'Quase todo o tráfego da internet passa por cabos no fundo do mar; levar conexão a um país abre negócios, escolas e dados.',
    conceito: 'Redes, fluxos de informação e infraestrutura', bncc: ['EM13CHS202', 'EM13CHS206'] },
];

// Ações sempre disponíveis, fora da mão de cartas
const ACOES_FIXAS = ['missao_diplomatica'];
