// =====================================================================
//  GEOGRAFIA IRADA — territórios neutros do mapa
// =====================================================================
//  As seis potências (brasil, eua, china, ue, india, russia) ficam em potencias.js.
//  Aqui estão os 33 territórios que as potências disputam com INFLUÊNCIA (não com guerra).
//  Os números são uma aproximação didática de dados reais (ONU, PNUD, Banco Mundial,
//  Global Carbon Project) e ficam na escala do jogo:
//    populacao (milhões) · desenvolvimento ≈ IDH × 100 · estabilidade 0–100 ·
//    vulnerabilidade climática 0–100 · conflito 0 (paz) a 3 (guerra aberta) ·
//    recursos = o que o território produz por mandato para a potência parceira ·
//    emissoes (Gt de CO₂ por ano) · floresta = emissões de desmatamento (Gt/ano) ·
//    influencia = laços que já existem em 2026 (cada ponto é um tijolo no mapa) ·
//    partes = potências que são parte direta do conflito em 2026 (a mediação delas é mais difícil) ·
//    artigo = o artigo do nome, para as frases saírem certas ("no Sahel", "nas Ilhas do Pacífico", "em Taiwan").
//  Conflitos de 2026 conferidos na pesquisa de 01/10/2026 (CFR Global Conflict Tracker, ONU, ACNUR, Al Jazeera).
//  continente: an (América do Norte), as (América do Sul), eu (Europa), af (África),
//              ai (Ásia), oc (Oceania), po (polos).
// =====================================================================

const TERRITORIOS = [
  // ---------------- América do Norte ----------------
  { id: 'canada', nome: 'Canadá', artigo: 'o', continente: 'an', paises: 'Canadá',
    populacao: 41, desenvolvimento: 94, estabilidade: 90, vulnerabilidade: 25, conflito: 0,
    recursos: { energia: 1, minerais: 1, alimentos: 1 }, emissoes: .55, floresta: 0,
    influencia: { eua: 6, ue: 2 },
    descricao: 'Segundo maior país do mundo em área, com petróleo, minérios, trigo e florestas boreais. Vizinho e grande parceiro comercial dos EUA.' },
  { id: 'mexico', nome: 'México', artigo: 'o', continente: 'an', paises: 'México',
    populacao: 130, desenvolvimento: 78, estabilidade: 50, vulnerabilidade: 55, conflito: 0,
    recursos: { energia: 1, alimentos: 1 }, emissoes: .47, floresta: 0,
    influencia: { eua: 4, china: 1, ue: 1 },
    descricao: 'Ponte entre a América do Norte e a América Latina. Exporta carros e eletrônicos para os EUA e é rota de migrantes rumo ao norte.' },
  { id: 'america_central', nome: 'América Central', artigo: 'a', continente: 'an', paises: 'Guatemala, Belize, Honduras, El Salvador, Nicarágua, Costa Rica e Panamá',
    populacao: 52, desenvolvimento: 68, estabilidade: 45, vulnerabilidade: 75, conflito: 0,
    recursos: { alimentos: 1 }, emissoes: .06, floresta: .02,
    influencia: { eua: 3, china: 1 },
    descricao: 'Istmo entre dois oceanos, cortado pelo Canal do Panamá. Sofre com furacões e secas, e muitos jovens migram para o norte.' },
  { id: 'caribe', nome: 'Caribe', artigo: 'o', continente: 'an', paises: 'Cuba, Haiti, República Dominicana, Jamaica, Bahamas, Trinidad e Tobago e outras ilhas',
    populacao: 44, desenvolvimento: 68, estabilidade: 38, vulnerabilidade: 85, conflito: 2,
    recursos: { alimentos: 1 }, emissoes: .06, floresta: 0,
    influencia: { eua: 2, brasil: 1, china: 1 },
    descricao: 'Ilhas muito expostas a furacões e à subida do mar. O Haiti vive uma grave crise de violência de gangues e fome.' },
  { id: 'groenlandia', nome: 'Groenlândia e Ártico', artigo: 'a', continente: 'an', paises: 'Groenlândia (território autônomo da Dinamarca)',
    populacao: .06, desenvolvimento: 85, estabilidade: 80, vulnerabilidade: 85, conflito: 0,
    recursos: { minerais: 1 }, emissoes: 0, floresta: 0,
    influencia: { ue: 3, eua: 2 },
    descricao: 'A maior ilha do mundo, coberta por um enorme manto de gelo que está derretendo. O degelo abre rotas marítimas e acesso a minérios no Ártico.' },

  // ---------------- América do Sul ----------------
  { id: 'andes', nome: 'Países Andinos', artigo: 'os', continente: 'as', paises: 'Colômbia, Equador, Peru e Bolívia',
    populacao: 117, desenvolvimento: 76, estabilidade: 50, vulnerabilidade: 60, conflito: 0,
    recursos: { minerais: 2, alimentos: 1 }, emissoes: .25, floresta: .15,
    influencia: { brasil: 2, china: 2, eua: 2 },
    descricao: 'Os Andes guardam cobre, prata e parte do "Triângulo do Lítio". Peru, Colômbia e Bolívia também têm parte da Floresta Amazônica.' },
  { id: 'venezuela_guianas', nome: 'Venezuela e Guianas', artigo: 'a', continente: 'as', paises: 'Venezuela, Guiana e Suriname',
    populacao: 30, desenvolvimento: 68, estabilidade: 30, vulnerabilidade: 45, conflito: 1,
    recursos: { energia: 2 }, emissoes: .1, floresta: .05,
    influencia: { brasil: 2, china: 2, russia: 2, eua: 1 },
    // conflito 1: em 03/01/2026, uma operação militar dos EUA capturou Nicolás Maduro; Essequibo na CIJ sem sentença (Al Jazeera; CIJ)
    descricao: 'A Venezuela tem as maiores reservas provadas de petróleo do mundo, e a Guiana virou um novo produtor. A Venezuela reivindica a região do Essequibo, que a Guiana administra. Em janeiro de 2026, uma operação militar dos EUA capturou o presidente Nicolás Maduro.' },
  { id: 'cone_sul', nome: 'Cone Sul', artigo: 'o', continente: 'as', paises: 'Argentina, Chile, Uruguai e Paraguai',
    populacao: 76, desenvolvimento: 83, estabilidade: 65, vulnerabilidade: 35, conflito: 0,
    recursos: { alimentos: 2, minerais: 1 }, emissoes: .3, floresta: .05,
    influencia: { brasil: 5, ue: 2, china: 2, eua: 1 },
    descricao: 'Grandes produtores de grãos e carne, com lítio e cobre nos Andes. Argentina, Uruguai e Paraguai formam o Mercosul com o Brasil.' },

  // ---------------- Europa ----------------
  { id: 'reino_unido', nome: 'Reino Unido e Noruega', artigo: 'o', continente: 'eu', paises: 'Reino Unido, Noruega, Islândia e Suíça',
    populacao: 84, desenvolvimento: 94, estabilidade: 82, vulnerabilidade: 20, conflito: 0,
    recursos: { tecnologia: 1, energia: 1 }, emissoes: .4, floresta: 0,
    influencia: { eua: 4, ue: 4 },
    descricao: 'Países europeus fora da União Europeia. O Reino Unido saiu da UE em 2020 e tem assento permanente, com veto, no Conselho de Segurança da ONU.' },
  { id: 'balcas', nome: 'Balcãs', artigo: 'os', continente: 'eu', paises: 'Sérvia, Bósnia e Herzegovina, Montenegro, Macedônia do Norte, Albânia e Kosovo',
    populacao: 17, desenvolvimento: 80, estabilidade: 55, vulnerabilidade: 30, conflito: 0,
    recursos: { alimentos: 1 }, emissoes: .1, floresta: 0,
    influencia: { ue: 5, russia: 2, china: 1 },
    descricao: 'Região que se fragmentou com o fim da Iugoslávia nos anos 1990. Quase todos querem entrar na União Europeia.' },
  { id: 'leste_europeu', nome: 'Leste Europeu', artigo: 'o', continente: 'eu', paises: 'Ucrânia, Belarus e Moldávia',
    populacao: 45, desenvolvimento: 76, estabilidade: 20, vulnerabilidade: 30, conflito: 3,
    recursos: { alimentos: 2 }, emissoes: .2, floresta: 0,
    influencia: { ue: 3, russia: 3, eua: 2 }, partes: ['russia'], // guerra desde a invasão russa de 24/02/2022, sem cessar-fogo em set/2026 (Al Jazeera)
    descricao: 'Grande celeiro de trigo e milho. A Ucrânia foi invadida pela Rússia em 2022; Belarus é aliada de Moscou; Ucrânia e Moldávia são candidatas à UE.' },

  // ---------------- África ----------------
  { id: 'norte_africa', nome: 'Norte da África', artigo: 'o', continente: 'af', paises: 'Marrocos, Saara Ocidental, Argélia, Tunísia, Líbia e Egito',
    populacao: 210, desenvolvimento: 72, estabilidade: 45, vulnerabilidade: 75, conflito: 1,
    recursos: { energia: 2 }, emissoes: .6, floresta: 0,
    influencia: { ue: 3, china: 2, russia: 1, eua: 1 },
    descricao: 'Ponte entre a África e a Europa, com gás e petróleo na Argélia e na Líbia e o Canal de Suez no Egito. A Líbia segue dividida desde 2011.' },
  { id: 'sahel', nome: 'Sahel', artigo: 'o', continente: 'af', paises: 'Mauritânia, Mali, Burkina Faso, Níger e Chade',
    populacao: 110, desenvolvimento: 40, estabilidade: 20, vulnerabilidade: 92, conflito: 2,
    recursos: { minerais: 1 }, emissoes: .03, floresta: 0,
    influencia: { russia: 3, china: 2, ue: 1 },
    descricao: 'Faixa semiárida ao sul do Saara, uma das regiões mais afetadas pelo aquecimento. Golpes militares e grupos armados deslocaram milhões de pessoas.' },
  { id: 'africa_ocidental', nome: 'África Ocidental', artigo: 'a', continente: 'af', paises: 'Nigéria, Gana, Costa do Marfim, Senegal, Guiné, Serra Leoa, Libéria, Togo, Benin, Gâmbia, Guiné-Bissau e Cabo Verde',
    populacao: 400, desenvolvimento: 52, estabilidade: 45, vulnerabilidade: 75, conflito: 1,
    recursos: { energia: 1, alimentos: 1, minerais: 1 }, emissoes: .25, floresta: .05,
    influencia: { ue: 2, china: 2, eua: 1, brasil: 1 },
    descricao: 'A Nigéria é o país mais populoso da África e grande produtor de petróleo; Gana e Costa do Marfim lideram o cacau. Guiné-Bissau e Cabo Verde falam português.' },
  { id: 'africa_central', nome: 'África Central', artigo: 'a', continente: 'af', paises: 'RD Congo, Congo, República Centro-Africana, Camarões, Gabão, Guiné Equatorial e São Tomé e Príncipe',
    populacao: 145, desenvolvimento: 47, estabilidade: 25, vulnerabilidade: 65, conflito: 2,
    recursos: { minerais: 3 }, emissoes: .05, floresta: .15,
    influencia: { china: 3, russia: 1, ue: 1, eua: 1 },
    descricao: 'Guarda a segunda maior floresta tropical do mundo, a da Bacia do Congo, e o cobalto das baterias. O leste da RD Congo vive um conflito armado há décadas.' },
  { id: 'africa_oriental', nome: 'África Oriental', artigo: 'a', continente: 'af', paises: 'Etiópia, Sudão, Sudão do Sul, Somália, Eritreia, Djibuti, Quênia, Uganda, Tanzânia, Ruanda e Burundi',
    populacao: 430, desenvolvimento: 50, estabilidade: 28, vulnerabilidade: 88, conflito: 3,
    recursos: { alimentos: 1 }, emissoes: .07, floresta: 0,
    influencia: { china: 3, india: 2, eua: 1, ue: 1 },
    descricao: 'Berço da humanidade e região de secas severas. A guerra civil no Sudão, iniciada em 2023, criou uma das maiores crises de deslocamento do mundo.' },
  { id: 'africa_austral', nome: 'África Austral', artigo: 'a', continente: 'af', paises: 'Angola, Moçambique, Namíbia, Botsuana, Zâmbia, Zimbábue, Malawi, Madagascar e Maurício',
    populacao: 210, desenvolvimento: 55, estabilidade: 50, vulnerabilidade: 75, conflito: 1,
    recursos: { minerais: 2, energia: 1 }, emissoes: .08, floresta: 0,
    influencia: { china: 2, brasil: 2, ue: 1 },
    descricao: 'Cobre na Zâmbia, diamantes em Botsuana e petróleo em Angola. Angola e Moçambique falam português e têm laços históricos com o Brasil.' },
  { id: 'africa_do_sul', nome: 'África do Sul', artigo: 'a', continente: 'af', paises: 'África do Sul, Lesoto e Essuatíni',
    populacao: 67, desenvolvimento: 74, estabilidade: 55, vulnerabilidade: 55, conflito: 0,
    recursos: { minerais: 2, energia: 1 }, emissoes: .4, floresta: 0,
    influencia: { china: 2, ue: 2, india: 1, brasil: 1, eua: 1, russia: 1 },
    descricao: 'Economia mais industrializada da África, membro do BRICS e do G20. Grande produtora de platina e ainda muito dependente do carvão.' },

  // ---------------- Ásia ----------------
  { id: 'turquia', nome: 'Turquia e Cáucaso', artigo: 'a', continente: 'ai', paises: 'Turquia, Geórgia, Armênia e Azerbaijão',
    populacao: 102, desenvolvimento: 83, estabilidade: 55, vulnerabilidade: 45, conflito: 0,
    recursos: { tecnologia: 1, alimentos: 1 }, emissoes: .5, floresta: 0,
    influencia: { ue: 3, russia: 2, eua: 2 },
    descricao: 'A Turquia, membro da OTAN, controla os estreitos entre o Mar Negro e o Mediterrâneo. O Azerbaijão exporta petróleo e gás.' },
  { id: 'golfo', nome: 'Península Arábica', artigo: 'a', continente: 'ai', paises: 'Arábia Saudita, Emirados Árabes Unidos, Catar, Kuwait, Bahrein, Omã e Iêmen',
    populacao: 97, desenvolvimento: 82, estabilidade: 55, vulnerabilidade: 70, conflito: 2,
    recursos: { energia: 3 }, emissoes: 1.0, floresta: 0,
    influencia: { eua: 3, china: 2, india: 2, russia: 1 },
    // conflito 2: os houthis retomaram os ataques em 2026 e tomaram a costa iemenita do Mar Vermelho em 10 e 11/09/2026 (Al Jazeera)
    descricao: 'Maior região exportadora de petróleo, ao lado do Estreito de Ormuz. No Iêmen, a guerra causou uma das piores crises humanitárias do século, e em 2026 os houthis tomaram a costa do Mar Vermelho.' },
  { id: 'levante', nome: 'Levante e Iraque', artigo: 'o', continente: 'ai', paises: 'Israel, Palestina, Líbano, Síria, Jordânia e Iraque',
    populacao: 103, desenvolvimento: 70, estabilidade: 25, vulnerabilidade: 65, conflito: 2,
    recursos: { energia: 1 }, emissoes: .4, floresta: 0,
    influencia: { eua: 2, russia: 1, ue: 1, china: 1 },
    descricao: 'Terra de povos e religiões muito antigas. A guerra em Gaza, a crise no Líbano e a reconstrução da Síria marcam a região; o Iraque exporta petróleo.' },
  { id: 'ira', nome: 'Irã', artigo: 'o', continente: 'ai', paises: 'Irã',
    populacao: 91, desenvolvimento: 79, estabilidade: 35, vulnerabilidade: 65, conflito: 2,
    recursos: { energia: 2 }, emissoes: .8, floresta: 0,
    // conflito 2: ataques de EUA e Israel em 28/02/2026; o cessar-fogo ruiu em 08/07/2026 e seguiam ataques esporádicos em set/2026 (CFR)
    influencia: { russia: 3, china: 3, india: 1 }, partes: ['eua'],
    descricao: 'Grande produtor de petróleo e gás às margens do Estreito de Ormuz. Em fevereiro de 2026, ataques dos EUA e de Israel abriram uma guerra; o Irã retaliou e chegou a fechar o estreito. O programa nuclear e as sanções seguem sem acordo.' },
  { id: 'asia_central', nome: 'Ásia Central e Mongólia', artigo: 'a', continente: 'ai', paises: 'Cazaquistão, Uzbequistão, Turcomenistão, Quirguistão, Tadjiquistão e Mongólia',
    populacao: 85, desenvolvimento: 75, estabilidade: 55, vulnerabilidade: 60, conflito: 0,
    recursos: { energia: 1, minerais: 1 }, emissoes: .5, floresta: 0,
    influencia: { russia: 5, china: 3 },
    descricao: 'Coração da antiga Rota da Seda, sem saída para o mar. O Cazaquistão é o maior produtor de urânio do mundo; o Mar de Aral quase secou.' },
  { id: 'afeg_paquistao', nome: 'Paquistão e Afeganistão', artigo: 'o', continente: 'ai', paises: 'Paquistão e Afeganistão',
    populacao: 290, desenvolvimento: 52, estabilidade: 25, vulnerabilidade: 88, conflito: 1,
    recursos: { alimentos: 1 }, emissoes: .25, floresta: 0,
    influencia: { china: 3, eua: 1, russia: 1 },
    descricao: 'O Paquistão tem armas nucleares e rivalidade histórica com a Índia pela Caxemira. As enchentes de 2022 cobriram um terço do país.' },
  { id: 'sul_asia', nome: 'Sul da Ásia', artigo: 'o', continente: 'ai', paises: 'Bangladesh, Nepal, Butão, Sri Lanka e Maldivas',
    populacao: 227, desenvolvimento: 67, estabilidade: 50, vulnerabilidade: 92, conflito: 0,
    recursos: { alimentos: 1 }, emissoes: .15, floresta: 0,
    influencia: { india: 5, china: 2 },
    descricao: 'Bangladesh é um dos países mais densamente povoados e vulneráveis à subida do mar; as Maldivas podem ficar submersas. A região produz muita roupa para o mundo.' },
  { id: 'taiwan', nome: 'Taiwan', artigo: '', continente: 'ai', paises: 'Taiwan (status político disputado)',
    populacao: 23, desenvolvimento: 92, estabilidade: 70, vulnerabilidade: 45, conflito: 0,
    recursos: { tecnologia: 3 }, emissoes: .27, floresta: 0,
    influencia: { eua: 3, china: 2 },
    descricao: 'Ilha que fabrica a maior parte dos chips mais avançados do mundo. A China a considera parte do seu território; o estreito de Taiwan é um foco de tensão.' },
  { id: 'japao_coreia', nome: 'Japão e Coreia do Sul', artigo: 'o', continente: 'ai', paises: 'Japão e Coreia do Sul',
    populacao: 176, desenvolvimento: 92, estabilidade: 85, vulnerabilidade: 45, conflito: 0,
    recursos: { tecnologia: 3 }, emissoes: 1.6, floresta: 0,
    influencia: { eua: 4, china: 2, ue: 1, india: 1 },
    descricao: 'Potências tecnológicas (carros, robôs, chips, cultura pop) aliadas dos EUA. Têm poucos recursos naturais e importam quase toda a energia.' },
  { id: 'coreia_norte', nome: 'Coreia do Norte', artigo: 'a', continente: 'ai', paises: 'Coreia do Norte',
    populacao: 26, desenvolvimento: 45, estabilidade: 50, vulnerabilidade: 55, conflito: 0,
    recursos: { minerais: 1 }, emissoes: .05, floresta: 0,
    influencia: { china: 5, russia: 2 },
    descricao: 'Regime fechado e autoritário, com programa de mísseis e armas nucleares. A península coreana está dividida desde a guerra de 1950–1953.' },
  { id: 'sudeste_continental', nome: 'Sudeste Asiático', artigo: 'o', continente: 'ai', paises: 'Vietnã, Tailândia, Mianmar, Camboja e Laos',
    populacao: 250, desenvolvimento: 70, estabilidade: 45, vulnerabilidade: 78, conflito: 2,
    recursos: { alimentos: 2, tecnologia: 1 }, emissoes: .75, floresta: .05,
    influencia: { china: 3, eua: 1, india: 1 },
    descricao: 'Grande produtor de arroz e polo de fábricas de eletrônicos. Em Mianmar, a guerra civil se agravou depois do golpe militar de 2021.' },
  { id: 'sudeste_insular', nome: 'Indonésia e Filipinas', artigo: 'a', continente: 'ai', paises: 'Indonésia, Filipinas, Malásia, Singapura, Brunei e Timor-Leste',
    populacao: 437, desenvolvimento: 73, estabilidade: 60, vulnerabilidade: 72, conflito: 0,
    recursos: { minerais: 2, energia: 1, alimentos: 1 }, emissoes: .95, floresta: .25,
    influencia: { china: 3, eua: 2, india: 1 },
    descricao: 'Milhares de ilhas no caminho do Estreito de Malaca, por onde passa boa parte do comércio mundial. A Indonésia lidera em níquel e entrou no BRICS em 2025.' },

  // ---------------- Oceania ----------------
  { id: 'australia', nome: 'Austrália e Nova Zelândia', artigo: 'a', continente: 'oc', paises: 'Austrália e Nova Zelândia',
    populacao: 32, desenvolvimento: 94, estabilidade: 85, vulnerabilidade: 55, conflito: 0,
    recursos: { minerais: 2, energia: 1, alimentos: 1 }, emissoes: .4, floresta: 0,
    influencia: { eua: 4, ue: 1, china: 2 },
    descricao: 'Grandes exportadores de minério de ferro, lítio, carvão e carne. Incêndios florestais e secas estão mais fortes com o aquecimento.' },
  { id: 'pacifico', nome: 'Ilhas do Pacífico', artigo: 'as', continente: 'oc', paises: 'Papua-Nova Guiné, Fiji, Ilhas Salomão, Vanuatu, Samoa, Tonga, Kiribati, Tuvalu e outras',
    populacao: 13, desenvolvimento: 58, estabilidade: 55, vulnerabilidade: 100, conflito: 0,
    recursos: { alimentos: 1 }, emissoes: .01, floresta: .02,
    influencia: { eua: 2, china: 2, ue: 1 },
    descricao: 'Países que quase não emitem gases de efeito estufa, mas podem perder território com a subida do mar. Tuvalu já negocia como manter seu povo e sua nação.' },

  // ---------------- Polos ----------------
  { id: 'antartida', nome: 'Antártida', artigo: 'a', continente: 'po', paises: 'Continente sem país, protegido pelo Tratado da Antártida (1959)',
    populacao: 0, desenvolvimento: 0, estabilidade: 100, vulnerabilidade: 0, conflito: 0,
    recursos: {}, emissoes: 0, floresta: 0, protegido: true,
    influencia: {},
    descricao: 'Ninguém é dono da Antártida: o Tratado da Antártida reserva o continente para a paz e a ciência e proíbe a mineração. Guarda quase 70% da água doce do planeta, em gelo.' },
];
